<?php
/**
 * MobileApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Crossly\Test\Api;

use \Crossly\Configuration;
use \Crossly\ApiException;
use \Crossly\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MobileApiTest Class Doc Comment
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MobileApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createMobilePushTest
     *
     * Fire a no-op test push to this user's devices..
     *
     */
    public function testCreateMobilePushTest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createMobilePushToken
     *
     * Register an Expo push token for this user..
     *
     */
    public function testCreateMobilePushToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteMobilePushToken
     *
     * Clear ALL registered push tokens for this user..
     *
     */
    public function testDeleteMobilePushToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMobilePushTokens
     *
     * List registered Expo push tokens (masked)..
     *
     */
    public function testListMobilePushTokens()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
