<?php
/**
 * CreateCbxAdCreditPurchaseResponseTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Crossly\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateCbxAdCreditPurchaseResponseTest Class Doc Comment
 *
 * @category    Class
 * @description CreateCbxAdCreditPurchaseResponse
 * @package     Crossly
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateCbxAdCreditPurchaseResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateCbxAdCreditPurchaseResponse"
     */
    public function testCreateCbxAdCreditPurchaseResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "credit_cents"
     */
    public function testPropertyCreditCents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "base_units_paid"
     */
    public function testPropertyBaseUnitsPaid()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cents_per_token"
     */
    public function testPropertyCentsPerToken()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "balance_cents"
     */
    public function testPropertyBalanceCents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "duplicate"
     */
    public function testPropertyDuplicate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
