<?php
/**
 * GetSpatialPublicResponseProfileItemSizeTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Crossly\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetSpatialPublicResponseProfileItemSizeTest Class Doc Comment
 *
 * @category    Class
 * @description Fallback physical size of one item. Used when the catalog does not publish  real dimensions for this product. See the module docblock: where the  catalog knows, the catalog wins.
 * @package     Crossly
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetSpatialPublicResponseProfileItemSizeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetSpatialPublicResponseProfileItemSize"
     */
    public function testGetSpatialPublicResponseProfileItemSize()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "x"
     */
    public function testPropertyX()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "y"
     */
    public function testPropertyY()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "z"
     */
    public function testPropertyZ()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
