<?php
/**
 * CreatePlatformAccountHistoryImportResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly\Buyer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Buyer\Model;

use \ArrayAccess;
use \Crossly\Buyer\ObjectSerializer;

/**
 * CreatePlatformAccountHistoryImportResponse Class Doc Comment
 *
 * @category Class
 * @package  Crossly\Buyer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class CreatePlatformAccountHistoryImportResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreatePlatformAccountHistoryImportResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'pending_accounts' => 'float',
        'ledger_fired' => 'bool',
        'listings_fired' => 'bool',
        'ok' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'pending_accounts' => null,
        'ledger_fired' => null,
        'listings_fired' => null,
        'ok' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'pending_accounts' => 'pendingAccounts',
        'ledger_fired' => 'ledgerFired',
        'listings_fired' => 'listingsFired',
        'ok' => 'ok'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'pending_accounts' => 'setPendingAccounts',
        'ledger_fired' => 'setLedgerFired',
        'listings_fired' => 'setListingsFired',
        'ok' => 'setOk'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'pending_accounts' => 'getPendingAccounts',
        'ledger_fired' => 'getLedgerFired',
        'listings_fired' => 'getListingsFired',
        'ok' => 'getOk'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['pending_accounts'] = $data['pending_accounts'] ?? null;
        $this->container['ledger_fired'] = $data['ledger_fired'] ?? null;
        $this->container['listings_fired'] = $data['listings_fired'] ?? null;
        $this->container['ok'] = $data['ok'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['pending_accounts'] === null) {
            $invalidProperties[] = "'pending_accounts' can't be null";
        }
        if ($this->container['ledger_fired'] === null) {
            $invalidProperties[] = "'ledger_fired' can't be null";
        }
        if ($this->container['listings_fired'] === null) {
            $invalidProperties[] = "'listings_fired' can't be null";
        }
        if ($this->container['ok'] === null) {
            $invalidProperties[] = "'ok' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets pending_accounts
     *
     * @return float
     */
    public function getPendingAccounts()
    {
        return $this->container['pending_accounts'];
    }

    /**
     * Sets pending_accounts
     *
     * @param float $pending_accounts pending_accounts
     *
     * @return self
     */
    public function setPendingAccounts($pending_accounts)
    {
        $this->container['pending_accounts'] = $pending_accounts;

        return $this;
    }

    /**
     * Gets ledger_fired
     *
     * @return bool
     */
    public function getLedgerFired()
    {
        return $this->container['ledger_fired'];
    }

    /**
     * Sets ledger_fired
     *
     * @param bool $ledger_fired ledger_fired
     *
     * @return self
     */
    public function setLedgerFired($ledger_fired)
    {
        $this->container['ledger_fired'] = $ledger_fired;

        return $this;
    }

    /**
     * Gets listings_fired
     *
     * @return bool
     */
    public function getListingsFired()
    {
        return $this->container['listings_fired'];
    }

    /**
     * Sets listings_fired
     *
     * @param bool $listings_fired listings_fired
     *
     * @return self
     */
    public function setListingsFired($listings_fired)
    {
        $this->container['listings_fired'] = $listings_fired;

        return $this;
    }

    /**
     * Gets ok
     *
     * @return bool
     */
    public function getOk()
    {
        return $this->container['ok'];
    }

    /**
     * Sets ok
     *
     * @param bool $ok ok
     *
     * @return self
     */
    public function setOk($ok)
    {
        $this->container['ok'] = $ok;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


