<?php
/**
 * GetConnectionHealthResponseLiveness
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly\Buyer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Buyer\Model;

use \ArrayAccess;
use \Crossly\Buyer\ObjectSerializer;

/**
 * GetConnectionHealthResponseLiveness Class Doc Comment
 *
 * @category Class
 * @package  Crossly\Buyer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class GetConnectionHealthResponseLiveness implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetConnectionHealthResponse_liveness';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'last_browser_push_at' => 'string',
        'last_browser_push_ago' => 'string',
        'last_synced_at' => 'string',
        'last_used_at' => 'string',
        'last_used_ago' => 'string',
        'auth_failure_streak' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'last_browser_push_at' => null,
        'last_browser_push_ago' => null,
        'last_synced_at' => null,
        'last_used_at' => null,
        'last_used_ago' => null,
        'auth_failure_streak' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'last_browser_push_at' => 'lastBrowserPushAt',
        'last_browser_push_ago' => 'lastBrowserPushAgo',
        'last_synced_at' => 'lastSyncedAt',
        'last_used_at' => 'lastUsedAt',
        'last_used_ago' => 'lastUsedAgo',
        'auth_failure_streak' => 'authFailureStreak'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'last_browser_push_at' => 'setLastBrowserPushAt',
        'last_browser_push_ago' => 'setLastBrowserPushAgo',
        'last_synced_at' => 'setLastSyncedAt',
        'last_used_at' => 'setLastUsedAt',
        'last_used_ago' => 'setLastUsedAgo',
        'auth_failure_streak' => 'setAuthFailureStreak'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'last_browser_push_at' => 'getLastBrowserPushAt',
        'last_browser_push_ago' => 'getLastBrowserPushAgo',
        'last_synced_at' => 'getLastSyncedAt',
        'last_used_at' => 'getLastUsedAt',
        'last_used_ago' => 'getLastUsedAgo',
        'auth_failure_streak' => 'getAuthFailureStreak'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['last_browser_push_at'] = $data['last_browser_push_at'] ?? null;
        $this->container['last_browser_push_ago'] = $data['last_browser_push_ago'] ?? null;
        $this->container['last_synced_at'] = $data['last_synced_at'] ?? null;
        $this->container['last_used_at'] = $data['last_used_at'] ?? null;
        $this->container['last_used_ago'] = $data['last_used_ago'] ?? null;
        $this->container['auth_failure_streak'] = $data['auth_failure_streak'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['last_browser_push_ago'] === null) {
            $invalidProperties[] = "'last_browser_push_ago' can't be null";
        }
        if ($this->container['last_used_ago'] === null) {
            $invalidProperties[] = "'last_used_ago' can't be null";
        }
        if ($this->container['auth_failure_streak'] === null) {
            $invalidProperties[] = "'auth_failure_streak' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets last_browser_push_at
     *
     * @return string|null
     */
    public function getLastBrowserPushAt()
    {
        return $this->container['last_browser_push_at'];
    }

    /**
     * Sets last_browser_push_at
     *
     * @param string|null $last_browser_push_at The clean \"the browser pushed cookies\" signal.
     *
     * @return self
     */
    public function setLastBrowserPushAt($last_browser_push_at)
    {
        $this->container['last_browser_push_at'] = $last_browser_push_at;

        return $this;
    }

    /**
     * Gets last_browser_push_ago
     *
     * @return string
     */
    public function getLastBrowserPushAgo()
    {
        return $this->container['last_browser_push_ago'];
    }

    /**
     * Sets last_browser_push_ago
     *
     * @param string $last_browser_push_ago last_browser_push_ago
     *
     * @return self
     */
    public function setLastBrowserPushAgo($last_browser_push_ago)
    {
        $this->container['last_browser_push_ago'] = $last_browser_push_ago;

        return $this;
    }

    /**
     * Gets last_synced_at
     *
     * @return string|null
     */
    public function getLastSyncedAt()
    {
        return $this->container['last_synced_at'];
    }

    /**
     * Sets last_synced_at
     *
     * @param string|null $last_synced_at Also stamped by the executor on any successful server-side call, so it is NOT evidence the extension is alive. Exposed for debugging only.
     *
     * @return self
     */
    public function setLastSyncedAt($last_synced_at)
    {
        $this->container['last_synced_at'] = $last_synced_at;

        return $this;
    }

    /**
     * Gets last_used_at
     *
     * @return string|null
     */
    public function getLastUsedAt()
    {
        return $this->container['last_used_at'];
    }

    /**
     * Sets last_used_at
     *
     * @param string|null $last_used_at Last server-exec attempt, success or fail.
     *
     * @return self
     */
    public function setLastUsedAt($last_used_at)
    {
        $this->container['last_used_at'] = $last_used_at;

        return $this;
    }

    /**
     * Gets last_used_ago
     *
     * @return string
     */
    public function getLastUsedAgo()
    {
        return $this->container['last_used_ago'];
    }

    /**
     * Sets last_used_ago
     *
     * @param string $last_used_ago last_used_ago
     *
     * @return self
     */
    public function setLastUsedAgo($last_used_ago)
    {
        $this->container['last_used_ago'] = $last_used_ago;

        return $this;
    }

    /**
     * Gets auth_failure_streak
     *
     * @return float
     */
    public function getAuthFailureStreak()
    {
        return $this->container['auth_failure_streak'];
    }

    /**
     * Sets auth_failure_streak
     *
     * @param float $auth_failure_streak auth_failure_streak
     *
     * @return self
     */
    public function setAuthFailureStreak($auth_failure_streak)
    {
        $this->container['auth_failure_streak'] = $auth_failure_streak;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


