<?php
/**
 * GetMileageSummaryResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly\Buyer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Buyer\Model;

use \ArrayAccess;
use \Crossly\Buyer\ObjectSerializer;

/**
 * GetMileageSummaryResponse Class Doc Comment
 *
 * @category Class
 * @package  Crossly\Buyer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class GetMileageSummaryResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetMileageSummaryResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'year' => 'float',
        'rate_per_mile' => 'float',
        'total_miles' => 'float',
        'deduction' => 'float',
        'entry_count' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'year' => null,
        'rate_per_mile' => null,
        'total_miles' => null,
        'deduction' => null,
        'entry_count' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'year' => 'year',
        'rate_per_mile' => 'ratePerMile',
        'total_miles' => 'totalMiles',
        'deduction' => 'deduction',
        'entry_count' => 'entryCount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'year' => 'setYear',
        'rate_per_mile' => 'setRatePerMile',
        'total_miles' => 'setTotalMiles',
        'deduction' => 'setDeduction',
        'entry_count' => 'setEntryCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'year' => 'getYear',
        'rate_per_mile' => 'getRatePerMile',
        'total_miles' => 'getTotalMiles',
        'deduction' => 'getDeduction',
        'entry_count' => 'getEntryCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['year'] = $data['year'] ?? null;
        $this->container['rate_per_mile'] = $data['rate_per_mile'] ?? null;
        $this->container['total_miles'] = $data['total_miles'] ?? null;
        $this->container['deduction'] = $data['deduction'] ?? null;
        $this->container['entry_count'] = $data['entry_count'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['year'] === null) {
            $invalidProperties[] = "'year' can't be null";
        }
        if ($this->container['rate_per_mile'] === null) {
            $invalidProperties[] = "'rate_per_mile' can't be null";
        }
        if ($this->container['total_miles'] === null) {
            $invalidProperties[] = "'total_miles' can't be null";
        }
        if ($this->container['deduction'] === null) {
            $invalidProperties[] = "'deduction' can't be null";
        }
        if ($this->container['entry_count'] === null) {
            $invalidProperties[] = "'entry_count' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets year
     *
     * @return float
     */
    public function getYear()
    {
        return $this->container['year'];
    }

    /**
     * Sets year
     *
     * @param float $year year
     *
     * @return self
     */
    public function setYear($year)
    {
        $this->container['year'] = $year;

        return $this;
    }

    /**
     * Gets rate_per_mile
     *
     * @return float
     */
    public function getRatePerMile()
    {
        return $this->container['rate_per_mile'];
    }

    /**
     * Sets rate_per_mile
     *
     * @param float $rate_per_mile rate_per_mile
     *
     * @return self
     */
    public function setRatePerMile($rate_per_mile)
    {
        $this->container['rate_per_mile'] = $rate_per_mile;

        return $this;
    }

    /**
     * Gets total_miles
     *
     * @return float
     */
    public function getTotalMiles()
    {
        return $this->container['total_miles'];
    }

    /**
     * Sets total_miles
     *
     * @param float $total_miles total_miles
     *
     * @return self
     */
    public function setTotalMiles($total_miles)
    {
        $this->container['total_miles'] = $total_miles;

        return $this;
    }

    /**
     * Gets deduction
     *
     * @return float
     */
    public function getDeduction()
    {
        return $this->container['deduction'];
    }

    /**
     * Sets deduction
     *
     * @param float $deduction deduction
     *
     * @return self
     */
    public function setDeduction($deduction)
    {
        $this->container['deduction'] = $deduction;

        return $this;
    }

    /**
     * Gets entry_count
     *
     * @return float
     */
    public function getEntryCount()
    {
        return $this->container['entry_count'];
    }

    /**
     * Sets entry_count
     *
     * @param float $entry_count entry_count
     *
     * @return self
     */
    public function setEntryCount($entry_count)
    {
        $this->container['entry_count'] = $entry_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


