<?php
/**
 * GetSpatialPublicResponseSolvedPlacements
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly\Buyer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Buyer\Model;

use \ArrayAccess;
use \Crossly\Buyer\ObjectSerializer;

/**
 * GetSpatialPublicResponseSolvedPlacements Class Doc Comment
 *
 * @category Class
 * @package  Crossly\Buyer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class GetSpatialPublicResponseSolvedPlacements implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetSpatialPublicResponse_solved_placements';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'item_id' => 'string',
        'unit_id' => 'string',
        'container_key' => 'string',
        'container_index' => 'float',
        'slot_index' => 'float',
        'position' => 'object',
        'group_path' => 'string[]',
        'pinned' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'item_id' => null,
        'unit_id' => null,
        'container_key' => null,
        'container_index' => null,
        'slot_index' => null,
        'position' => null,
        'group_path' => null,
        'pinned' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'item_id' => 'itemId',
        'unit_id' => 'unitId',
        'container_key' => 'containerKey',
        'container_index' => 'containerIndex',
        'slot_index' => 'slotIndex',
        'position' => 'position',
        'group_path' => 'groupPath',
        'pinned' => 'pinned'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'item_id' => 'setItemId',
        'unit_id' => 'setUnitId',
        'container_key' => 'setContainerKey',
        'container_index' => 'setContainerIndex',
        'slot_index' => 'setSlotIndex',
        'position' => 'setPosition',
        'group_path' => 'setGroupPath',
        'pinned' => 'setPinned'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'item_id' => 'getItemId',
        'unit_id' => 'getUnitId',
        'container_key' => 'getContainerKey',
        'container_index' => 'getContainerIndex',
        'slot_index' => 'getSlotIndex',
        'position' => 'getPosition',
        'group_path' => 'getGroupPath',
        'pinned' => 'getPinned'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['item_id'] = $data['item_id'] ?? null;
        $this->container['unit_id'] = $data['unit_id'] ?? null;
        $this->container['container_key'] = $data['container_key'] ?? null;
        $this->container['container_index'] = $data['container_index'] ?? null;
        $this->container['slot_index'] = $data['slot_index'] ?? null;
        $this->container['position'] = $data['position'] ?? null;
        $this->container['group_path'] = $data['group_path'] ?? null;
        $this->container['pinned'] = $data['pinned'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['item_id'] === null) {
            $invalidProperties[] = "'item_id' can't be null";
        }
        if ($this->container['container_key'] === null) {
            $invalidProperties[] = "'container_key' can't be null";
        }
        if ($this->container['container_index'] === null) {
            $invalidProperties[] = "'container_index' can't be null";
        }
        if ($this->container['slot_index'] === null) {
            $invalidProperties[] = "'slot_index' can't be null";
        }
        if ($this->container['position'] === null) {
            $invalidProperties[] = "'position' can't be null";
        }
        if ($this->container['group_path'] === null) {
            $invalidProperties[] = "'group_path' can't be null";
        }
        if ($this->container['pinned'] === null) {
            $invalidProperties[] = "'pinned' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets item_id
     *
     * @return string
     */
    public function getItemId()
    {
        return $this->container['item_id'];
    }

    /**
     * Sets item_id
     *
     * @param string $item_id item_id
     *
     * @return self
     */
    public function setItemId($item_id)
    {
        $this->container['item_id'] = $item_id;

        return $this;
    }

    /**
     * Gets unit_id
     *
     * @return string|null
     */
    public function getUnitId()
    {
        return $this->container['unit_id'];
    }

    /**
     * Sets unit_id
     *
     * @param string|null $unit_id unit_id
     *
     * @return self
     */
    public function setUnitId($unit_id)
    {
        $this->container['unit_id'] = $unit_id;

        return $this;
    }

    /**
     * Gets container_key
     *
     * @return string
     */
    public function getContainerKey()
    {
        return $this->container['container_key'];
    }

    /**
     * Sets container_key
     *
     * @param string $container_key container_key
     *
     * @return self
     */
    public function setContainerKey($container_key)
    {
        $this->container['container_key'] = $container_key;

        return $this;
    }

    /**
     * Gets container_index
     *
     * @return float
     */
    public function getContainerIndex()
    {
        return $this->container['container_index'];
    }

    /**
     * Sets container_index
     *
     * @param float $container_index container_index
     *
     * @return self
     */
    public function setContainerIndex($container_index)
    {
        $this->container['container_index'] = $container_index;

        return $this;
    }

    /**
     * Gets slot_index
     *
     * @return float
     */
    public function getSlotIndex()
    {
        return $this->container['slot_index'];
    }

    /**
     * Sets slot_index
     *
     * @param float $slot_index slot_index
     *
     * @return self
     */
    public function setSlotIndex($slot_index)
    {
        $this->container['slot_index'] = $slot_index;

        return $this;
    }

    /**
     * Gets position
     *
     * @return object
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param object $position Local position inside the container, metres.
     *
     * @return self
     */
    public function setPosition($position)
    {
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets group_path
     *
     * @return string[]
     */
    public function getGroupPath()
    {
        return $this->container['group_path'];
    }

    /**
     * Sets group_path
     *
     * @param string[] $group_path group_path
     *
     * @return self
     */
    public function setGroupPath($group_path)
    {
        $this->container['group_path'] = $group_path;

        return $this;
    }

    /**
     * Gets pinned
     *
     * @return bool
     */
    public function getPinned()
    {
        return $this->container['pinned'];
    }

    /**
     * Sets pinned
     *
     * @param bool $pinned pinned
     *
     * @return self
     */
    public function setPinned($pinned)
    {
        $this->container['pinned'] = $pinned;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


