<?php
/**
 * GetAnalyticDashboardResponseSellThroughTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly\Buyer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Crossly\Buyer\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetAnalyticDashboardResponseSellThroughTest Class Doc Comment
 *
 * @category    Class
 * @description The context the bare rate can&#39;t carry. &#x60;tooYoungToJudge&#x60; is the  important one: a cohort measured the day its window closed has had no  time to sell, and a low number there means \&quot;wait\&quot;, not \&quot;bad buys\&quot; — a  seller acting on it would stop sourcing for no reason.
 * @package     Crossly\Buyer
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetAnalyticDashboardResponseSellThroughTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetAnalyticDashboardResponseSellThrough"
     */
    public function testGetAnalyticDashboardResponseSellThrough()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cohort_size"
     */
    public function testPropertyCohortSize()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cohort_sold"
     */
    public function testPropertyCohortSold()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "maturity_days"
     */
    public function testPropertyMaturityDays()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "too_young_to_judge"
     */
    public function testPropertyTooYoungToJudge()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
