<?php
/**
 * GetTaxScheduleCResponseExpensesTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly\Buyer
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Buyer API
 *
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Crossly\Buyer\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetTaxScheduleCResponseExpensesTest Class Doc Comment
 *
 * @category    Class
 * @description GetTaxScheduleCResponseExpenses
 * @package     Crossly\Buyer
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetTaxScheduleCResponseExpensesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetTaxScheduleCResponseExpenses"
     */
    public function testGetTaxScheduleCResponseExpenses()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "platform_fees"
     */
    public function testPropertyPlatformFees()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shipping_expenses"
     */
    public function testPropertyShippingExpenses()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cost_of_goods_sold"
     */
    public function testPropertyCostOfGoodsSold()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "car_and_truck_mileage"
     */
    public function testPropertyCarAndTruckMileage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "car_and_truck_miles"
     */
    public function testPropertyCarAndTruckMiles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
