<?php
/**
 * CreateListingCombineResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Model;

use \ArrayAccess;
use \Crossly\ObjectSerializer;

/**
 * CreateListingCombineResponse Class Doc Comment
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class CreateListingCombineResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateListingCombineResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'keep_listing_id' => 'string',
        'merged_listing_ids' => 'string[]',
        'new_quantity_available' => 'float',
        'units_moved' => 'float',
        'delist_jobs_dispatched' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'keep_listing_id' => null,
        'merged_listing_ids' => null,
        'new_quantity_available' => null,
        'units_moved' => null,
        'delist_jobs_dispatched' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'keep_listing_id' => 'keepListingId',
        'merged_listing_ids' => 'mergedListingIds',
        'new_quantity_available' => 'newQuantityAvailable',
        'units_moved' => 'unitsMoved',
        'delist_jobs_dispatched' => 'delistJobsDispatched'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'keep_listing_id' => 'setKeepListingId',
        'merged_listing_ids' => 'setMergedListingIds',
        'new_quantity_available' => 'setNewQuantityAvailable',
        'units_moved' => 'setUnitsMoved',
        'delist_jobs_dispatched' => 'setDelistJobsDispatched'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'keep_listing_id' => 'getKeepListingId',
        'merged_listing_ids' => 'getMergedListingIds',
        'new_quantity_available' => 'getNewQuantityAvailable',
        'units_moved' => 'getUnitsMoved',
        'delist_jobs_dispatched' => 'getDelistJobsDispatched'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['keep_listing_id'] = $data['keep_listing_id'] ?? null;
        $this->container['merged_listing_ids'] = $data['merged_listing_ids'] ?? null;
        $this->container['new_quantity_available'] = $data['new_quantity_available'] ?? null;
        $this->container['units_moved'] = $data['units_moved'] ?? null;
        $this->container['delist_jobs_dispatched'] = $data['delist_jobs_dispatched'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['keep_listing_id'] === null) {
            $invalidProperties[] = "'keep_listing_id' can't be null";
        }
        if ($this->container['merged_listing_ids'] === null) {
            $invalidProperties[] = "'merged_listing_ids' can't be null";
        }
        if ($this->container['new_quantity_available'] === null) {
            $invalidProperties[] = "'new_quantity_available' can't be null";
        }
        if ($this->container['units_moved'] === null) {
            $invalidProperties[] = "'units_moved' can't be null";
        }
        if ($this->container['delist_jobs_dispatched'] === null) {
            $invalidProperties[] = "'delist_jobs_dispatched' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets keep_listing_id
     *
     * @return string
     */
    public function getKeepListingId()
    {
        return $this->container['keep_listing_id'];
    }

    /**
     * Sets keep_listing_id
     *
     * @param string $keep_listing_id keep_listing_id
     *
     * @return self
     */
    public function setKeepListingId($keep_listing_id)
    {
        $this->container['keep_listing_id'] = $keep_listing_id;

        return $this;
    }

    /**
     * Gets merged_listing_ids
     *
     * @return string[]
     */
    public function getMergedListingIds()
    {
        return $this->container['merged_listing_ids'];
    }

    /**
     * Sets merged_listing_ids
     *
     * @param string[] $merged_listing_ids Listings archived into the keeper.
     *
     * @return self
     */
    public function setMergedListingIds($merged_listing_ids)
    {
        $this->container['merged_listing_ids'] = $merged_listing_ids;

        return $this;
    }

    /**
     * Gets new_quantity_available
     *
     * @return float
     */
    public function getNewQuantityAvailable()
    {
        return $this->container['new_quantity_available'];
    }

    /**
     * Sets new_quantity_available
     *
     * @param float $new_quantity_available Stock on the keeper's item after summing.
     *
     * @return self
     */
    public function setNewQuantityAvailable($new_quantity_available)
    {
        $this->container['new_quantity_available'] = $new_quantity_available;

        return $this;
    }

    /**
     * Gets units_moved
     *
     * @return float
     */
    public function getUnitsMoved()
    {
        return $this->container['units_moved'];
    }

    /**
     * Sets units_moved
     *
     * @param float $units_moved Units moved off the merged items.
     *
     * @return self
     */
    public function setUnitsMoved($units_moved)
    {
        $this->container['units_moved'] = $units_moved;

        return $this;
    }

    /**
     * Gets delist_jobs_dispatched
     *
     * @return float
     */
    public function getDelistJobsDispatched()
    {
        return $this->container['delist_jobs_dispatched'];
    }

    /**
     * Sets delist_jobs_dispatched
     *
     * @param float $delist_jobs_dispatched Delist jobs dispatched for the merged listings' live platforms.
     *
     * @return self
     */
    public function setDelistJobsDispatched($delist_jobs_dispatched)
    {
        $this->container['delist_jobs_dispatched'] = $delist_jobs_dispatched;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


