<?php
/**
 * CreateAiCategorizeFromImageResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Model;

use \ArrayAccess;
use \Crossly\ObjectSerializer;

/**
 * CreateAiCategorizeFromImageResponse Class Doc Comment
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class CreateAiCategorizeFromImageResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateAiCategorizeFromImageResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'category' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'sub_category' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'brand' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'condition' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'colors' => '\Crossly\Model\CreateAiGenerateListingResponseColors',
        'size' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'tags' => '\Crossly\Model\CreateAiGenerateListingResponseColors',
        'suggested_title' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'material' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'style' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'pattern' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'department' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'gender' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'item_type' => '\Crossly\Model\CreateAiGenerateListingResponseDescription',
        'size_system' => '\Crossly\Model\CreateAiGenerateListingResponseDescription'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'category' => null,
        'sub_category' => null,
        'brand' => null,
        'condition' => null,
        'colors' => null,
        'size' => null,
        'tags' => null,
        'suggested_title' => null,
        'material' => null,
        'style' => null,
        'pattern' => null,
        'department' => null,
        'gender' => null,
        'item_type' => null,
        'size_system' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'category' => 'category',
        'sub_category' => 'subCategory',
        'brand' => 'brand',
        'condition' => 'condition',
        'colors' => 'colors',
        'size' => 'size',
        'tags' => 'tags',
        'suggested_title' => 'suggestedTitle',
        'material' => 'material',
        'style' => 'style',
        'pattern' => 'pattern',
        'department' => 'department',
        'gender' => 'gender',
        'item_type' => 'itemType',
        'size_system' => 'sizeSystem'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'category' => 'setCategory',
        'sub_category' => 'setSubCategory',
        'brand' => 'setBrand',
        'condition' => 'setCondition',
        'colors' => 'setColors',
        'size' => 'setSize',
        'tags' => 'setTags',
        'suggested_title' => 'setSuggestedTitle',
        'material' => 'setMaterial',
        'style' => 'setStyle',
        'pattern' => 'setPattern',
        'department' => 'setDepartment',
        'gender' => 'setGender',
        'item_type' => 'setItemType',
        'size_system' => 'setSizeSystem'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'category' => 'getCategory',
        'sub_category' => 'getSubCategory',
        'brand' => 'getBrand',
        'condition' => 'getCondition',
        'colors' => 'getColors',
        'size' => 'getSize',
        'tags' => 'getTags',
        'suggested_title' => 'getSuggestedTitle',
        'material' => 'getMaterial',
        'style' => 'getStyle',
        'pattern' => 'getPattern',
        'department' => 'getDepartment',
        'gender' => 'getGender',
        'item_type' => 'getItemType',
        'size_system' => 'getSizeSystem'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['category'] = $data['category'] ?? null;
        $this->container['sub_category'] = $data['sub_category'] ?? null;
        $this->container['brand'] = $data['brand'] ?? null;
        $this->container['condition'] = $data['condition'] ?? null;
        $this->container['colors'] = $data['colors'] ?? null;
        $this->container['size'] = $data['size'] ?? null;
        $this->container['tags'] = $data['tags'] ?? null;
        $this->container['suggested_title'] = $data['suggested_title'] ?? null;
        $this->container['material'] = $data['material'] ?? null;
        $this->container['style'] = $data['style'] ?? null;
        $this->container['pattern'] = $data['pattern'] ?? null;
        $this->container['department'] = $data['department'] ?? null;
        $this->container['gender'] = $data['gender'] ?? null;
        $this->container['item_type'] = $data['item_type'] ?? null;
        $this->container['size_system'] = $data['size_system'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets category
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getCategory()
    {
        return $this->container['category'];
    }

    /**
     * Sets category
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $category category
     *
     * @return self
     */
    public function setCategory($category)
    {
        $this->container['category'] = $category;

        return $this;
    }

    /**
     * Gets sub_category
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getSubCategory()
    {
        return $this->container['sub_category'];
    }

    /**
     * Sets sub_category
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $sub_category sub_category
     *
     * @return self
     */
    public function setSubCategory($sub_category)
    {
        $this->container['sub_category'] = $sub_category;

        return $this;
    }

    /**
     * Gets brand
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $brand brand
     *
     * @return self
     */
    public function setBrand($brand)
    {
        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets condition
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getCondition()
    {
        return $this->container['condition'];
    }

    /**
     * Sets condition
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $condition condition
     *
     * @return self
     */
    public function setCondition($condition)
    {
        $this->container['condition'] = $condition;

        return $this;
    }

    /**
     * Gets colors
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseColors|null
     */
    public function getColors()
    {
        return $this->container['colors'];
    }

    /**
     * Sets colors
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseColors|null $colors colors
     *
     * @return self
     */
    public function setColors($colors)
    {
        $this->container['colors'] = $colors;

        return $this;
    }

    /**
     * Gets size
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $size size
     *
     * @return self
     */
    public function setSize($size)
    {
        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseColors|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseColors|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets suggested_title
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getSuggestedTitle()
    {
        return $this->container['suggested_title'];
    }

    /**
     * Sets suggested_title
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $suggested_title suggested_title
     *
     * @return self
     */
    public function setSuggestedTitle($suggested_title)
    {
        $this->container['suggested_title'] = $suggested_title;

        return $this;
    }

    /**
     * Gets material
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getMaterial()
    {
        return $this->container['material'];
    }

    /**
     * Sets material
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $material material
     *
     * @return self
     */
    public function setMaterial($material)
    {
        $this->container['material'] = $material;

        return $this;
    }

    /**
     * Gets style
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getStyle()
    {
        return $this->container['style'];
    }

    /**
     * Sets style
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $style style
     *
     * @return self
     */
    public function setStyle($style)
    {
        $this->container['style'] = $style;

        return $this;
    }

    /**
     * Gets pattern
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getPattern()
    {
        return $this->container['pattern'];
    }

    /**
     * Sets pattern
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $pattern pattern
     *
     * @return self
     */
    public function setPattern($pattern)
    {
        $this->container['pattern'] = $pattern;

        return $this;
    }

    /**
     * Gets department
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getDepartment()
    {
        return $this->container['department'];
    }

    /**
     * Sets department
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $department department
     *
     * @return self
     */
    public function setDepartment($department)
    {
        $this->container['department'] = $department;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $gender gender
     *
     * @return self
     */
    public function setGender($gender)
    {
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets item_type
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getItemType()
    {
        return $this->container['item_type'];
    }

    /**
     * Sets item_type
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $item_type item_type
     *
     * @return self
     */
    public function setItemType($item_type)
    {
        $this->container['item_type'] = $item_type;

        return $this;
    }

    /**
     * Gets size_system
     *
     * @return \Crossly\Model\CreateAiGenerateListingResponseDescription|null
     */
    public function getSizeSystem()
    {
        return $this->container['size_system'];
    }

    /**
     * Sets size_system
     *
     * @param \Crossly\Model\CreateAiGenerateListingResponseDescription|null $size_system size_system
     *
     * @return self
     */
    public function setSizeSystem($size_system)
    {
        $this->container['size_system'] = $size_system;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


