<?php
/**
 * GetBuyerPreferenceResponse
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Model;

use \ArrayAccess;
use \Crossly\ObjectSerializer;

/**
 * GetBuyerPreferenceResponse Class Doc Comment
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class GetBuyerPreferenceResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetBuyerPreferenceResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'retailers' => '\Crossly\Model\GetBuyerPreferenceResponseRetailers[]',
        'brands' => '\Crossly\Model\GetBuyerPreferenceResponseBrands[]',
        'price_band' => '\Crossly\Model\GetBuyerPreferenceResponsePriceBand',
        'match_rate' => 'float',
        'observations' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'retailers' => null,
        'brands' => null,
        'price_band' => null,
        'match_rate' => null,
        'observations' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'retailers' => 'retailers',
        'brands' => 'brands',
        'price_band' => 'priceBand',
        'match_rate' => 'matchRate',
        'observations' => 'observations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'retailers' => 'setRetailers',
        'brands' => 'setBrands',
        'price_band' => 'setPriceBand',
        'match_rate' => 'setMatchRate',
        'observations' => 'setObservations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'retailers' => 'getRetailers',
        'brands' => 'getBrands',
        'price_band' => 'getPriceBand',
        'match_rate' => 'getMatchRate',
        'observations' => 'getObservations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['retailers'] = $data['retailers'] ?? null;
        $this->container['brands'] = $data['brands'] ?? null;
        $this->container['price_band'] = $data['price_band'] ?? null;
        $this->container['match_rate'] = $data['match_rate'] ?? null;
        $this->container['observations'] = $data['observations'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['retailers'] === null) {
            $invalidProperties[] = "'retailers' can't be null";
        }
        if ($this->container['brands'] === null) {
            $invalidProperties[] = "'brands' can't be null";
        }
        if ($this->container['observations'] === null) {
            $invalidProperties[] = "'observations' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets retailers
     *
     * @return \Crossly\Model\GetBuyerPreferenceResponseRetailers[]
     */
    public function getRetailers()
    {
        return $this->container['retailers'];
    }

    /**
     * Sets retailers
     *
     * @param \Crossly\Model\GetBuyerPreferenceResponseRetailers[] $retailers Retailers they shop, most-seen first.
     *
     * @return self
     */
    public function setRetailers($retailers)
    {
        $this->container['retailers'] = $retailers;

        return $this;
    }

    /**
     * Gets brands
     *
     * @return \Crossly\Model\GetBuyerPreferenceResponseBrands[]
     */
    public function getBrands()
    {
        return $this->container['brands'];
    }

    /**
     * Sets brands
     *
     * @param \Crossly\Model\GetBuyerPreferenceResponseBrands[] $brands What they look at, by catalog brand where we could resolve one.
     *
     * @return self
     */
    public function setBrands($brands)
    {
        $this->container['brands'] = $brands;

        return $this;
    }

    /**
     * Gets price_band
     *
     * @return \Crossly\Model\GetBuyerPreferenceResponsePriceBand|null
     */
    public function getPriceBand()
    {
        return $this->container['price_band'];
    }

    /**
     * Sets price_band
     *
     * @param \Crossly\Model\GetBuyerPreferenceResponsePriceBand|null $price_band price_band
     *
     * @return self
     */
    public function setPriceBand($price_band)
    {
        $this->container['price_band'] = $price_band;

        return $this;
    }

    /**
     * Gets match_rate
     *
     * @return float|null
     */
    public function getMatchRate()
    {
        return $this->container['match_rate'];
    }

    /**
     * Sets match_rate
     *
     * @param float|null $match_rate How much of what they want we can actually supply.
     *
     * @return self
     */
    public function setMatchRate($match_rate)
    {
        $this->container['match_rate'] = $match_rate;

        return $this;
    }

    /**
     * Gets observations
     *
     * @return float
     */
    public function getObservations()
    {
        return $this->container['observations'];
    }

    /**
     * Sets observations
     *
     * @param float $observations observations
     *
     * @return self
     */
    public function setObservations($observations)
    {
        $this->container['observations'] = $observations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


