<?php
/**
 * GetListingResponsePlatformListings
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Model;

use \ArrayAccess;
use \Crossly\ObjectSerializer;

/**
 * GetListingResponsePlatformListings Class Doc Comment
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class GetListingResponsePlatformListings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetListingResponse_platformListings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'user_id' => 'string',
        'quantity' => 'float',
        'status' => 'string',
        'platform' => 'string',
        'error_message' => 'string',
        'listing_id' => 'string',
        'account_slot' => 'float',
        'delisted_at' => '\DateTime',
        'sold_at' => '\DateTime',
        'inventory_item_id' => 'string',
        'platform_listing_id' => 'string',
        'platform_listing_url' => 'string',
        'stock_location' => 'string',
        'listed_at' => '\DateTime',
        'shared_at' => '\DateTime',
        'delist_reason' => 'string',
        'last_checked_at' => '\DateTime',
        'views' => 'float',
        'favorites' => 'float',
        'comments_count' => 'float',
        'last_stats_synced_at' => '\DateTime',
        'hashtags' => 'string[]',
        'is_draft' => 'bool',
        'scheduled_publish_at' => '\DateTime',
        'is_dutch_auction' => 'bool',
        'dutch_start_cents' => 'float',
        'dutch_floor_cents' => 'float',
        'dutch_ends_at' => '\DateTime',
        'is_pre_order' => 'bool',
        'expected_ship_by' => 'string',
        'preorder_deposit_percent_bps' => 'float',
        'boosted_at' => '\DateTime',
        'image_caption' => 'string',
        'duration_days' => 'float',
        'ends_at' => '\DateTime',
        'best_offer_enabled' => 'bool',
        'best_offer_auto_accept_cents' => 'float',
        'best_offer_auto_decline_cents' => 'float',
        'aesthetic_tags' => 'string[]',
        'allows_local_pickup' => 'bool',
        'pickup_radius_miles' => 'float',
        'pickup_lat' => 'string',
        'pickup_lng' => 'string',
        'refurbished_tier' => 'string',
        'charity_slug' => 'string',
        'charity_percent_bps' => 'float',
        'crossly_return_policy_id' => 'string',
        'crossly_shipping_policy_id' => 'string',
        'crossly_payment_policy_id' => 'string',
        'retail_price_cents' => 'float',
        'restricted_countries' => 'string[]',
        'auction_extend_seconds' => 'float',
        'authentication_provider_slug' => 'string',
        'authentication_required' => 'bool',
        'has_variants' => 'bool',
        'charity_id' => 'string',
        'min_order_quantity' => 'float',
        'wholesale_unit_price_cents' => 'float',
        'wholesale_min_quantity' => 'float',
        'auction_reserve_cents' => 'float',
        'is_gtc' => 'bool',
        'handling_time_days' => 'float',
        'item_location' => 'string',
        'item_location_zip' => 'string',
        'item_location_country' => 'string',
        'declared_shipping_cost' => 'string',
        'return_policy_text' => 'string',
        'last_drift_checked_at' => '\DateTime',
        'verification_failed' => 'bool',
        'published_overrides' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'user_id' => null,
        'quantity' => null,
        'status' => null,
        'platform' => null,
        'error_message' => null,
        'listing_id' => null,
        'account_slot' => null,
        'delisted_at' => 'date-time',
        'sold_at' => 'date-time',
        'inventory_item_id' => null,
        'platform_listing_id' => null,
        'platform_listing_url' => null,
        'stock_location' => null,
        'listed_at' => 'date-time',
        'shared_at' => 'date-time',
        'delist_reason' => null,
        'last_checked_at' => 'date-time',
        'views' => null,
        'favorites' => null,
        'comments_count' => null,
        'last_stats_synced_at' => 'date-time',
        'hashtags' => null,
        'is_draft' => null,
        'scheduled_publish_at' => 'date-time',
        'is_dutch_auction' => null,
        'dutch_start_cents' => null,
        'dutch_floor_cents' => null,
        'dutch_ends_at' => 'date-time',
        'is_pre_order' => null,
        'expected_ship_by' => null,
        'preorder_deposit_percent_bps' => null,
        'boosted_at' => 'date-time',
        'image_caption' => null,
        'duration_days' => null,
        'ends_at' => 'date-time',
        'best_offer_enabled' => null,
        'best_offer_auto_accept_cents' => null,
        'best_offer_auto_decline_cents' => null,
        'aesthetic_tags' => null,
        'allows_local_pickup' => null,
        'pickup_radius_miles' => null,
        'pickup_lat' => null,
        'pickup_lng' => null,
        'refurbished_tier' => null,
        'charity_slug' => null,
        'charity_percent_bps' => null,
        'crossly_return_policy_id' => null,
        'crossly_shipping_policy_id' => null,
        'crossly_payment_policy_id' => null,
        'retail_price_cents' => null,
        'restricted_countries' => null,
        'auction_extend_seconds' => null,
        'authentication_provider_slug' => null,
        'authentication_required' => null,
        'has_variants' => null,
        'charity_id' => null,
        'min_order_quantity' => null,
        'wholesale_unit_price_cents' => null,
        'wholesale_min_quantity' => null,
        'auction_reserve_cents' => null,
        'is_gtc' => null,
        'handling_time_days' => null,
        'item_location' => null,
        'item_location_zip' => null,
        'item_location_country' => null,
        'declared_shipping_cost' => null,
        'return_policy_text' => null,
        'last_drift_checked_at' => 'date-time',
        'verification_failed' => null,
        'published_overrides' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'user_id' => 'userId',
        'quantity' => 'quantity',
        'status' => 'status',
        'platform' => 'platform',
        'error_message' => 'errorMessage',
        'listing_id' => 'listingId',
        'account_slot' => 'accountSlot',
        'delisted_at' => 'delistedAt',
        'sold_at' => 'soldAt',
        'inventory_item_id' => 'inventoryItemId',
        'platform_listing_id' => 'platformListingId',
        'platform_listing_url' => 'platformListingUrl',
        'stock_location' => 'stockLocation',
        'listed_at' => 'listedAt',
        'shared_at' => 'sharedAt',
        'delist_reason' => 'delistReason',
        'last_checked_at' => 'lastCheckedAt',
        'views' => 'views',
        'favorites' => 'favorites',
        'comments_count' => 'commentsCount',
        'last_stats_synced_at' => 'lastStatsSyncedAt',
        'hashtags' => 'hashtags',
        'is_draft' => 'isDraft',
        'scheduled_publish_at' => 'scheduledPublishAt',
        'is_dutch_auction' => 'isDutchAuction',
        'dutch_start_cents' => 'dutchStartCents',
        'dutch_floor_cents' => 'dutchFloorCents',
        'dutch_ends_at' => 'dutchEndsAt',
        'is_pre_order' => 'isPreOrder',
        'expected_ship_by' => 'expectedShipBy',
        'preorder_deposit_percent_bps' => 'preorderDepositPercentBps',
        'boosted_at' => 'boostedAt',
        'image_caption' => 'imageCaption',
        'duration_days' => 'durationDays',
        'ends_at' => 'endsAt',
        'best_offer_enabled' => 'bestOfferEnabled',
        'best_offer_auto_accept_cents' => 'bestOfferAutoAcceptCents',
        'best_offer_auto_decline_cents' => 'bestOfferAutoDeclineCents',
        'aesthetic_tags' => 'aestheticTags',
        'allows_local_pickup' => 'allowsLocalPickup',
        'pickup_radius_miles' => 'pickupRadiusMiles',
        'pickup_lat' => 'pickupLat',
        'pickup_lng' => 'pickupLng',
        'refurbished_tier' => 'refurbishedTier',
        'charity_slug' => 'charitySlug',
        'charity_percent_bps' => 'charityPercentBps',
        'crossly_return_policy_id' => 'crosslyReturnPolicyId',
        'crossly_shipping_policy_id' => 'crosslyShippingPolicyId',
        'crossly_payment_policy_id' => 'crosslyPaymentPolicyId',
        'retail_price_cents' => 'retailPriceCents',
        'restricted_countries' => 'restrictedCountries',
        'auction_extend_seconds' => 'auctionExtendSeconds',
        'authentication_provider_slug' => 'authenticationProviderSlug',
        'authentication_required' => 'authenticationRequired',
        'has_variants' => 'hasVariants',
        'charity_id' => 'charityId',
        'min_order_quantity' => 'minOrderQuantity',
        'wholesale_unit_price_cents' => 'wholesaleUnitPriceCents',
        'wholesale_min_quantity' => 'wholesaleMinQuantity',
        'auction_reserve_cents' => 'auctionReserveCents',
        'is_gtc' => 'isGtc',
        'handling_time_days' => 'handlingTimeDays',
        'item_location' => 'itemLocation',
        'item_location_zip' => 'itemLocationZip',
        'item_location_country' => 'itemLocationCountry',
        'declared_shipping_cost' => 'declaredShippingCost',
        'return_policy_text' => 'returnPolicyText',
        'last_drift_checked_at' => 'lastDriftCheckedAt',
        'verification_failed' => 'verificationFailed',
        'published_overrides' => 'publishedOverrides'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'user_id' => 'setUserId',
        'quantity' => 'setQuantity',
        'status' => 'setStatus',
        'platform' => 'setPlatform',
        'error_message' => 'setErrorMessage',
        'listing_id' => 'setListingId',
        'account_slot' => 'setAccountSlot',
        'delisted_at' => 'setDelistedAt',
        'sold_at' => 'setSoldAt',
        'inventory_item_id' => 'setInventoryItemId',
        'platform_listing_id' => 'setPlatformListingId',
        'platform_listing_url' => 'setPlatformListingUrl',
        'stock_location' => 'setStockLocation',
        'listed_at' => 'setListedAt',
        'shared_at' => 'setSharedAt',
        'delist_reason' => 'setDelistReason',
        'last_checked_at' => 'setLastCheckedAt',
        'views' => 'setViews',
        'favorites' => 'setFavorites',
        'comments_count' => 'setCommentsCount',
        'last_stats_synced_at' => 'setLastStatsSyncedAt',
        'hashtags' => 'setHashtags',
        'is_draft' => 'setIsDraft',
        'scheduled_publish_at' => 'setScheduledPublishAt',
        'is_dutch_auction' => 'setIsDutchAuction',
        'dutch_start_cents' => 'setDutchStartCents',
        'dutch_floor_cents' => 'setDutchFloorCents',
        'dutch_ends_at' => 'setDutchEndsAt',
        'is_pre_order' => 'setIsPreOrder',
        'expected_ship_by' => 'setExpectedShipBy',
        'preorder_deposit_percent_bps' => 'setPreorderDepositPercentBps',
        'boosted_at' => 'setBoostedAt',
        'image_caption' => 'setImageCaption',
        'duration_days' => 'setDurationDays',
        'ends_at' => 'setEndsAt',
        'best_offer_enabled' => 'setBestOfferEnabled',
        'best_offer_auto_accept_cents' => 'setBestOfferAutoAcceptCents',
        'best_offer_auto_decline_cents' => 'setBestOfferAutoDeclineCents',
        'aesthetic_tags' => 'setAestheticTags',
        'allows_local_pickup' => 'setAllowsLocalPickup',
        'pickup_radius_miles' => 'setPickupRadiusMiles',
        'pickup_lat' => 'setPickupLat',
        'pickup_lng' => 'setPickupLng',
        'refurbished_tier' => 'setRefurbishedTier',
        'charity_slug' => 'setCharitySlug',
        'charity_percent_bps' => 'setCharityPercentBps',
        'crossly_return_policy_id' => 'setCrosslyReturnPolicyId',
        'crossly_shipping_policy_id' => 'setCrosslyShippingPolicyId',
        'crossly_payment_policy_id' => 'setCrosslyPaymentPolicyId',
        'retail_price_cents' => 'setRetailPriceCents',
        'restricted_countries' => 'setRestrictedCountries',
        'auction_extend_seconds' => 'setAuctionExtendSeconds',
        'authentication_provider_slug' => 'setAuthenticationProviderSlug',
        'authentication_required' => 'setAuthenticationRequired',
        'has_variants' => 'setHasVariants',
        'charity_id' => 'setCharityId',
        'min_order_quantity' => 'setMinOrderQuantity',
        'wholesale_unit_price_cents' => 'setWholesaleUnitPriceCents',
        'wholesale_min_quantity' => 'setWholesaleMinQuantity',
        'auction_reserve_cents' => 'setAuctionReserveCents',
        'is_gtc' => 'setIsGtc',
        'handling_time_days' => 'setHandlingTimeDays',
        'item_location' => 'setItemLocation',
        'item_location_zip' => 'setItemLocationZip',
        'item_location_country' => 'setItemLocationCountry',
        'declared_shipping_cost' => 'setDeclaredShippingCost',
        'return_policy_text' => 'setReturnPolicyText',
        'last_drift_checked_at' => 'setLastDriftCheckedAt',
        'verification_failed' => 'setVerificationFailed',
        'published_overrides' => 'setPublishedOverrides'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'user_id' => 'getUserId',
        'quantity' => 'getQuantity',
        'status' => 'getStatus',
        'platform' => 'getPlatform',
        'error_message' => 'getErrorMessage',
        'listing_id' => 'getListingId',
        'account_slot' => 'getAccountSlot',
        'delisted_at' => 'getDelistedAt',
        'sold_at' => 'getSoldAt',
        'inventory_item_id' => 'getInventoryItemId',
        'platform_listing_id' => 'getPlatformListingId',
        'platform_listing_url' => 'getPlatformListingUrl',
        'stock_location' => 'getStockLocation',
        'listed_at' => 'getListedAt',
        'shared_at' => 'getSharedAt',
        'delist_reason' => 'getDelistReason',
        'last_checked_at' => 'getLastCheckedAt',
        'views' => 'getViews',
        'favorites' => 'getFavorites',
        'comments_count' => 'getCommentsCount',
        'last_stats_synced_at' => 'getLastStatsSyncedAt',
        'hashtags' => 'getHashtags',
        'is_draft' => 'getIsDraft',
        'scheduled_publish_at' => 'getScheduledPublishAt',
        'is_dutch_auction' => 'getIsDutchAuction',
        'dutch_start_cents' => 'getDutchStartCents',
        'dutch_floor_cents' => 'getDutchFloorCents',
        'dutch_ends_at' => 'getDutchEndsAt',
        'is_pre_order' => 'getIsPreOrder',
        'expected_ship_by' => 'getExpectedShipBy',
        'preorder_deposit_percent_bps' => 'getPreorderDepositPercentBps',
        'boosted_at' => 'getBoostedAt',
        'image_caption' => 'getImageCaption',
        'duration_days' => 'getDurationDays',
        'ends_at' => 'getEndsAt',
        'best_offer_enabled' => 'getBestOfferEnabled',
        'best_offer_auto_accept_cents' => 'getBestOfferAutoAcceptCents',
        'best_offer_auto_decline_cents' => 'getBestOfferAutoDeclineCents',
        'aesthetic_tags' => 'getAestheticTags',
        'allows_local_pickup' => 'getAllowsLocalPickup',
        'pickup_radius_miles' => 'getPickupRadiusMiles',
        'pickup_lat' => 'getPickupLat',
        'pickup_lng' => 'getPickupLng',
        'refurbished_tier' => 'getRefurbishedTier',
        'charity_slug' => 'getCharitySlug',
        'charity_percent_bps' => 'getCharityPercentBps',
        'crossly_return_policy_id' => 'getCrosslyReturnPolicyId',
        'crossly_shipping_policy_id' => 'getCrosslyShippingPolicyId',
        'crossly_payment_policy_id' => 'getCrosslyPaymentPolicyId',
        'retail_price_cents' => 'getRetailPriceCents',
        'restricted_countries' => 'getRestrictedCountries',
        'auction_extend_seconds' => 'getAuctionExtendSeconds',
        'authentication_provider_slug' => 'getAuthenticationProviderSlug',
        'authentication_required' => 'getAuthenticationRequired',
        'has_variants' => 'getHasVariants',
        'charity_id' => 'getCharityId',
        'min_order_quantity' => 'getMinOrderQuantity',
        'wholesale_unit_price_cents' => 'getWholesaleUnitPriceCents',
        'wholesale_min_quantity' => 'getWholesaleMinQuantity',
        'auction_reserve_cents' => 'getAuctionReserveCents',
        'is_gtc' => 'getIsGtc',
        'handling_time_days' => 'getHandlingTimeDays',
        'item_location' => 'getItemLocation',
        'item_location_zip' => 'getItemLocationZip',
        'item_location_country' => 'getItemLocationCountry',
        'declared_shipping_cost' => 'getDeclaredShippingCost',
        'return_policy_text' => 'getReturnPolicyText',
        'last_drift_checked_at' => 'getLastDriftCheckedAt',
        'verification_failed' => 'getVerificationFailed',
        'published_overrides' => 'getPublishedOverrides'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['user_id'] = $data['user_id'] ?? null;
        $this->container['quantity'] = $data['quantity'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
        $this->container['platform'] = $data['platform'] ?? null;
        $this->container['error_message'] = $data['error_message'] ?? null;
        $this->container['listing_id'] = $data['listing_id'] ?? null;
        $this->container['account_slot'] = $data['account_slot'] ?? null;
        $this->container['delisted_at'] = $data['delisted_at'] ?? null;
        $this->container['sold_at'] = $data['sold_at'] ?? null;
        $this->container['inventory_item_id'] = $data['inventory_item_id'] ?? null;
        $this->container['platform_listing_id'] = $data['platform_listing_id'] ?? null;
        $this->container['platform_listing_url'] = $data['platform_listing_url'] ?? null;
        $this->container['stock_location'] = $data['stock_location'] ?? null;
        $this->container['listed_at'] = $data['listed_at'] ?? null;
        $this->container['shared_at'] = $data['shared_at'] ?? null;
        $this->container['delist_reason'] = $data['delist_reason'] ?? null;
        $this->container['last_checked_at'] = $data['last_checked_at'] ?? null;
        $this->container['views'] = $data['views'] ?? null;
        $this->container['favorites'] = $data['favorites'] ?? null;
        $this->container['comments_count'] = $data['comments_count'] ?? null;
        $this->container['last_stats_synced_at'] = $data['last_stats_synced_at'] ?? null;
        $this->container['hashtags'] = $data['hashtags'] ?? null;
        $this->container['is_draft'] = $data['is_draft'] ?? null;
        $this->container['scheduled_publish_at'] = $data['scheduled_publish_at'] ?? null;
        $this->container['is_dutch_auction'] = $data['is_dutch_auction'] ?? null;
        $this->container['dutch_start_cents'] = $data['dutch_start_cents'] ?? null;
        $this->container['dutch_floor_cents'] = $data['dutch_floor_cents'] ?? null;
        $this->container['dutch_ends_at'] = $data['dutch_ends_at'] ?? null;
        $this->container['is_pre_order'] = $data['is_pre_order'] ?? null;
        $this->container['expected_ship_by'] = $data['expected_ship_by'] ?? null;
        $this->container['preorder_deposit_percent_bps'] = $data['preorder_deposit_percent_bps'] ?? null;
        $this->container['boosted_at'] = $data['boosted_at'] ?? null;
        $this->container['image_caption'] = $data['image_caption'] ?? null;
        $this->container['duration_days'] = $data['duration_days'] ?? null;
        $this->container['ends_at'] = $data['ends_at'] ?? null;
        $this->container['best_offer_enabled'] = $data['best_offer_enabled'] ?? null;
        $this->container['best_offer_auto_accept_cents'] = $data['best_offer_auto_accept_cents'] ?? null;
        $this->container['best_offer_auto_decline_cents'] = $data['best_offer_auto_decline_cents'] ?? null;
        $this->container['aesthetic_tags'] = $data['aesthetic_tags'] ?? null;
        $this->container['allows_local_pickup'] = $data['allows_local_pickup'] ?? null;
        $this->container['pickup_radius_miles'] = $data['pickup_radius_miles'] ?? null;
        $this->container['pickup_lat'] = $data['pickup_lat'] ?? null;
        $this->container['pickup_lng'] = $data['pickup_lng'] ?? null;
        $this->container['refurbished_tier'] = $data['refurbished_tier'] ?? null;
        $this->container['charity_slug'] = $data['charity_slug'] ?? null;
        $this->container['charity_percent_bps'] = $data['charity_percent_bps'] ?? null;
        $this->container['crossly_return_policy_id'] = $data['crossly_return_policy_id'] ?? null;
        $this->container['crossly_shipping_policy_id'] = $data['crossly_shipping_policy_id'] ?? null;
        $this->container['crossly_payment_policy_id'] = $data['crossly_payment_policy_id'] ?? null;
        $this->container['retail_price_cents'] = $data['retail_price_cents'] ?? null;
        $this->container['restricted_countries'] = $data['restricted_countries'] ?? null;
        $this->container['auction_extend_seconds'] = $data['auction_extend_seconds'] ?? null;
        $this->container['authentication_provider_slug'] = $data['authentication_provider_slug'] ?? null;
        $this->container['authentication_required'] = $data['authentication_required'] ?? null;
        $this->container['has_variants'] = $data['has_variants'] ?? null;
        $this->container['charity_id'] = $data['charity_id'] ?? null;
        $this->container['min_order_quantity'] = $data['min_order_quantity'] ?? null;
        $this->container['wholesale_unit_price_cents'] = $data['wholesale_unit_price_cents'] ?? null;
        $this->container['wholesale_min_quantity'] = $data['wholesale_min_quantity'] ?? null;
        $this->container['auction_reserve_cents'] = $data['auction_reserve_cents'] ?? null;
        $this->container['is_gtc'] = $data['is_gtc'] ?? null;
        $this->container['handling_time_days'] = $data['handling_time_days'] ?? null;
        $this->container['item_location'] = $data['item_location'] ?? null;
        $this->container['item_location_zip'] = $data['item_location_zip'] ?? null;
        $this->container['item_location_country'] = $data['item_location_country'] ?? null;
        $this->container['declared_shipping_cost'] = $data['declared_shipping_cost'] ?? null;
        $this->container['return_policy_text'] = $data['return_policy_text'] ?? null;
        $this->container['last_drift_checked_at'] = $data['last_drift_checked_at'] ?? null;
        $this->container['verification_failed'] = $data['verification_failed'] ?? null;
        $this->container['published_overrides'] = $data['published_overrides'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['user_id'] === null) {
            $invalidProperties[] = "'user_id' can't be null";
        }
        if ($this->container['quantity'] === null) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['platform'] === null) {
            $invalidProperties[] = "'platform' can't be null";
        }
        if ($this->container['listing_id'] === null) {
            $invalidProperties[] = "'listing_id' can't be null";
        }
        if ($this->container['account_slot'] === null) {
            $invalidProperties[] = "'account_slot' can't be null";
        }
        if ($this->container['platform_listing_id'] === null) {
            $invalidProperties[] = "'platform_listing_id' can't be null";
        }
        if ($this->container['stock_location'] === null) {
            $invalidProperties[] = "'stock_location' can't be null";
        }
        if ($this->container['views'] === null) {
            $invalidProperties[] = "'views' can't be null";
        }
        if ($this->container['favorites'] === null) {
            $invalidProperties[] = "'favorites' can't be null";
        }
        if ($this->container['comments_count'] === null) {
            $invalidProperties[] = "'comments_count' can't be null";
        }
        if ($this->container['is_draft'] === null) {
            $invalidProperties[] = "'is_draft' can't be null";
        }
        if ($this->container['is_dutch_auction'] === null) {
            $invalidProperties[] = "'is_dutch_auction' can't be null";
        }
        if ($this->container['is_pre_order'] === null) {
            $invalidProperties[] = "'is_pre_order' can't be null";
        }
        if ($this->container['best_offer_enabled'] === null) {
            $invalidProperties[] = "'best_offer_enabled' can't be null";
        }
        if ($this->container['allows_local_pickup'] === null) {
            $invalidProperties[] = "'allows_local_pickup' can't be null";
        }
        if ($this->container['authentication_required'] === null) {
            $invalidProperties[] = "'authentication_required' can't be null";
        }
        if ($this->container['has_variants'] === null) {
            $invalidProperties[] = "'has_variants' can't be null";
        }
        if ($this->container['min_order_quantity'] === null) {
            $invalidProperties[] = "'min_order_quantity' can't be null";
        }
        if ($this->container['is_gtc'] === null) {
            $invalidProperties[] = "'is_gtc' can't be null";
        }
        if ($this->container['handling_time_days'] === null) {
            $invalidProperties[] = "'handling_time_days' can't be null";
        }
        if ($this->container['verification_failed'] === null) {
            $invalidProperties[] = "'verification_failed' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return float
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param float $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets platform
     *
     * @return string
     */
    public function getPlatform()
    {
        return $this->container['platform'];
    }

    /**
     * Sets platform
     *
     * @param string $platform platform
     *
     * @return self
     */
    public function setPlatform($platform)
    {
        $this->container['platform'] = $platform;

        return $this;
    }

    /**
     * Gets error_message
     *
     * @return string|null
     */
    public function getErrorMessage()
    {
        return $this->container['error_message'];
    }

    /**
     * Sets error_message
     *
     * @param string|null $error_message error_message
     *
     * @return self
     */
    public function setErrorMessage($error_message)
    {
        $this->container['error_message'] = $error_message;

        return $this;
    }

    /**
     * Gets listing_id
     *
     * @return string
     */
    public function getListingId()
    {
        return $this->container['listing_id'];
    }

    /**
     * Sets listing_id
     *
     * @param string $listing_id listing_id
     *
     * @return self
     */
    public function setListingId($listing_id)
    {
        $this->container['listing_id'] = $listing_id;

        return $this;
    }

    /**
     * Gets account_slot
     *
     * @return float
     */
    public function getAccountSlot()
    {
        return $this->container['account_slot'];
    }

    /**
     * Sets account_slot
     *
     * @param float $account_slot account_slot
     *
     * @return self
     */
    public function setAccountSlot($account_slot)
    {
        $this->container['account_slot'] = $account_slot;

        return $this;
    }

    /**
     * Gets delisted_at
     *
     * @return \DateTime|null
     */
    public function getDelistedAt()
    {
        return $this->container['delisted_at'];
    }

    /**
     * Sets delisted_at
     *
     * @param \DateTime|null $delisted_at delisted_at
     *
     * @return self
     */
    public function setDelistedAt($delisted_at)
    {
        $this->container['delisted_at'] = $delisted_at;

        return $this;
    }

    /**
     * Gets sold_at
     *
     * @return \DateTime|null
     */
    public function getSoldAt()
    {
        return $this->container['sold_at'];
    }

    /**
     * Sets sold_at
     *
     * @param \DateTime|null $sold_at sold_at
     *
     * @return self
     */
    public function setSoldAt($sold_at)
    {
        $this->container['sold_at'] = $sold_at;

        return $this;
    }

    /**
     * Gets inventory_item_id
     *
     * @return string|null
     */
    public function getInventoryItemId()
    {
        return $this->container['inventory_item_id'];
    }

    /**
     * Sets inventory_item_id
     *
     * @param string|null $inventory_item_id inventory_item_id
     *
     * @return self
     */
    public function setInventoryItemId($inventory_item_id)
    {
        $this->container['inventory_item_id'] = $inventory_item_id;

        return $this;
    }

    /**
     * Gets platform_listing_id
     *
     * @return string
     */
    public function getPlatformListingId()
    {
        return $this->container['platform_listing_id'];
    }

    /**
     * Sets platform_listing_id
     *
     * @param string $platform_listing_id platform_listing_id
     *
     * @return self
     */
    public function setPlatformListingId($platform_listing_id)
    {
        $this->container['platform_listing_id'] = $platform_listing_id;

        return $this;
    }

    /**
     * Gets platform_listing_url
     *
     * @return string|null
     */
    public function getPlatformListingUrl()
    {
        return $this->container['platform_listing_url'];
    }

    /**
     * Sets platform_listing_url
     *
     * @param string|null $platform_listing_url platform_listing_url
     *
     * @return self
     */
    public function setPlatformListingUrl($platform_listing_url)
    {
        $this->container['platform_listing_url'] = $platform_listing_url;

        return $this;
    }

    /**
     * Gets stock_location
     *
     * @return string
     */
    public function getStockLocation()
    {
        return $this->container['stock_location'];
    }

    /**
     * Sets stock_location
     *
     * @param string $stock_location stock_location
     *
     * @return self
     */
    public function setStockLocation($stock_location)
    {
        $this->container['stock_location'] = $stock_location;

        return $this;
    }

    /**
     * Gets listed_at
     *
     * @return \DateTime|null
     */
    public function getListedAt()
    {
        return $this->container['listed_at'];
    }

    /**
     * Sets listed_at
     *
     * @param \DateTime|null $listed_at listed_at
     *
     * @return self
     */
    public function setListedAt($listed_at)
    {
        $this->container['listed_at'] = $listed_at;

        return $this;
    }

    /**
     * Gets shared_at
     *
     * @return \DateTime|null
     */
    public function getSharedAt()
    {
        return $this->container['shared_at'];
    }

    /**
     * Sets shared_at
     *
     * @param \DateTime|null $shared_at shared_at
     *
     * @return self
     */
    public function setSharedAt($shared_at)
    {
        $this->container['shared_at'] = $shared_at;

        return $this;
    }

    /**
     * Gets delist_reason
     *
     * @return string|null
     */
    public function getDelistReason()
    {
        return $this->container['delist_reason'];
    }

    /**
     * Sets delist_reason
     *
     * @param string|null $delist_reason delist_reason
     *
     * @return self
     */
    public function setDelistReason($delist_reason)
    {
        $this->container['delist_reason'] = $delist_reason;

        return $this;
    }

    /**
     * Gets last_checked_at
     *
     * @return \DateTime|null
     */
    public function getLastCheckedAt()
    {
        return $this->container['last_checked_at'];
    }

    /**
     * Sets last_checked_at
     *
     * @param \DateTime|null $last_checked_at last_checked_at
     *
     * @return self
     */
    public function setLastCheckedAt($last_checked_at)
    {
        $this->container['last_checked_at'] = $last_checked_at;

        return $this;
    }

    /**
     * Gets views
     *
     * @return float
     */
    public function getViews()
    {
        return $this->container['views'];
    }

    /**
     * Sets views
     *
     * @param float $views views
     *
     * @return self
     */
    public function setViews($views)
    {
        $this->container['views'] = $views;

        return $this;
    }

    /**
     * Gets favorites
     *
     * @return float
     */
    public function getFavorites()
    {
        return $this->container['favorites'];
    }

    /**
     * Sets favorites
     *
     * @param float $favorites favorites
     *
     * @return self
     */
    public function setFavorites($favorites)
    {
        $this->container['favorites'] = $favorites;

        return $this;
    }

    /**
     * Gets comments_count
     *
     * @return float
     */
    public function getCommentsCount()
    {
        return $this->container['comments_count'];
    }

    /**
     * Sets comments_count
     *
     * @param float $comments_count comments_count
     *
     * @return self
     */
    public function setCommentsCount($comments_count)
    {
        $this->container['comments_count'] = $comments_count;

        return $this;
    }

    /**
     * Gets last_stats_synced_at
     *
     * @return \DateTime|null
     */
    public function getLastStatsSyncedAt()
    {
        return $this->container['last_stats_synced_at'];
    }

    /**
     * Sets last_stats_synced_at
     *
     * @param \DateTime|null $last_stats_synced_at last_stats_synced_at
     *
     * @return self
     */
    public function setLastStatsSyncedAt($last_stats_synced_at)
    {
        $this->container['last_stats_synced_at'] = $last_stats_synced_at;

        return $this;
    }

    /**
     * Gets hashtags
     *
     * @return string[]|null
     */
    public function getHashtags()
    {
        return $this->container['hashtags'];
    }

    /**
     * Sets hashtags
     *
     * @param string[]|null $hashtags hashtags
     *
     * @return self
     */
    public function setHashtags($hashtags)
    {
        $this->container['hashtags'] = $hashtags;

        return $this;
    }

    /**
     * Gets is_draft
     *
     * @return bool
     */
    public function getIsDraft()
    {
        return $this->container['is_draft'];
    }

    /**
     * Sets is_draft
     *
     * @param bool $is_draft is_draft
     *
     * @return self
     */
    public function setIsDraft($is_draft)
    {
        $this->container['is_draft'] = $is_draft;

        return $this;
    }

    /**
     * Gets scheduled_publish_at
     *
     * @return \DateTime|null
     */
    public function getScheduledPublishAt()
    {
        return $this->container['scheduled_publish_at'];
    }

    /**
     * Sets scheduled_publish_at
     *
     * @param \DateTime|null $scheduled_publish_at scheduled_publish_at
     *
     * @return self
     */
    public function setScheduledPublishAt($scheduled_publish_at)
    {
        $this->container['scheduled_publish_at'] = $scheduled_publish_at;

        return $this;
    }

    /**
     * Gets is_dutch_auction
     *
     * @return bool
     */
    public function getIsDutchAuction()
    {
        return $this->container['is_dutch_auction'];
    }

    /**
     * Sets is_dutch_auction
     *
     * @param bool $is_dutch_auction is_dutch_auction
     *
     * @return self
     */
    public function setIsDutchAuction($is_dutch_auction)
    {
        $this->container['is_dutch_auction'] = $is_dutch_auction;

        return $this;
    }

    /**
     * Gets dutch_start_cents
     *
     * @return float|null
     */
    public function getDutchStartCents()
    {
        return $this->container['dutch_start_cents'];
    }

    /**
     * Sets dutch_start_cents
     *
     * @param float|null $dutch_start_cents dutch_start_cents
     *
     * @return self
     */
    public function setDutchStartCents($dutch_start_cents)
    {
        $this->container['dutch_start_cents'] = $dutch_start_cents;

        return $this;
    }

    /**
     * Gets dutch_floor_cents
     *
     * @return float|null
     */
    public function getDutchFloorCents()
    {
        return $this->container['dutch_floor_cents'];
    }

    /**
     * Sets dutch_floor_cents
     *
     * @param float|null $dutch_floor_cents dutch_floor_cents
     *
     * @return self
     */
    public function setDutchFloorCents($dutch_floor_cents)
    {
        $this->container['dutch_floor_cents'] = $dutch_floor_cents;

        return $this;
    }

    /**
     * Gets dutch_ends_at
     *
     * @return \DateTime|null
     */
    public function getDutchEndsAt()
    {
        return $this->container['dutch_ends_at'];
    }

    /**
     * Sets dutch_ends_at
     *
     * @param \DateTime|null $dutch_ends_at dutch_ends_at
     *
     * @return self
     */
    public function setDutchEndsAt($dutch_ends_at)
    {
        $this->container['dutch_ends_at'] = $dutch_ends_at;

        return $this;
    }

    /**
     * Gets is_pre_order
     *
     * @return bool
     */
    public function getIsPreOrder()
    {
        return $this->container['is_pre_order'];
    }

    /**
     * Sets is_pre_order
     *
     * @param bool $is_pre_order is_pre_order
     *
     * @return self
     */
    public function setIsPreOrder($is_pre_order)
    {
        $this->container['is_pre_order'] = $is_pre_order;

        return $this;
    }

    /**
     * Gets expected_ship_by
     *
     * @return string|null
     */
    public function getExpectedShipBy()
    {
        return $this->container['expected_ship_by'];
    }

    /**
     * Sets expected_ship_by
     *
     * @param string|null $expected_ship_by expected_ship_by
     *
     * @return self
     */
    public function setExpectedShipBy($expected_ship_by)
    {
        $this->container['expected_ship_by'] = $expected_ship_by;

        return $this;
    }

    /**
     * Gets preorder_deposit_percent_bps
     *
     * @return float|null
     */
    public function getPreorderDepositPercentBps()
    {
        return $this->container['preorder_deposit_percent_bps'];
    }

    /**
     * Sets preorder_deposit_percent_bps
     *
     * @param float|null $preorder_deposit_percent_bps preorder_deposit_percent_bps
     *
     * @return self
     */
    public function setPreorderDepositPercentBps($preorder_deposit_percent_bps)
    {
        $this->container['preorder_deposit_percent_bps'] = $preorder_deposit_percent_bps;

        return $this;
    }

    /**
     * Gets boosted_at
     *
     * @return \DateTime|null
     */
    public function getBoostedAt()
    {
        return $this->container['boosted_at'];
    }

    /**
     * Sets boosted_at
     *
     * @param \DateTime|null $boosted_at boosted_at
     *
     * @return self
     */
    public function setBoostedAt($boosted_at)
    {
        $this->container['boosted_at'] = $boosted_at;

        return $this;
    }

    /**
     * Gets image_caption
     *
     * @return string|null
     */
    public function getImageCaption()
    {
        return $this->container['image_caption'];
    }

    /**
     * Sets image_caption
     *
     * @param string|null $image_caption image_caption
     *
     * @return self
     */
    public function setImageCaption($image_caption)
    {
        $this->container['image_caption'] = $image_caption;

        return $this;
    }

    /**
     * Gets duration_days
     *
     * @return float|null
     */
    public function getDurationDays()
    {
        return $this->container['duration_days'];
    }

    /**
     * Sets duration_days
     *
     * @param float|null $duration_days duration_days
     *
     * @return self
     */
    public function setDurationDays($duration_days)
    {
        $this->container['duration_days'] = $duration_days;

        return $this;
    }

    /**
     * Gets ends_at
     *
     * @return \DateTime|null
     */
    public function getEndsAt()
    {
        return $this->container['ends_at'];
    }

    /**
     * Sets ends_at
     *
     * @param \DateTime|null $ends_at ends_at
     *
     * @return self
     */
    public function setEndsAt($ends_at)
    {
        $this->container['ends_at'] = $ends_at;

        return $this;
    }

    /**
     * Gets best_offer_enabled
     *
     * @return bool
     */
    public function getBestOfferEnabled()
    {
        return $this->container['best_offer_enabled'];
    }

    /**
     * Sets best_offer_enabled
     *
     * @param bool $best_offer_enabled best_offer_enabled
     *
     * @return self
     */
    public function setBestOfferEnabled($best_offer_enabled)
    {
        $this->container['best_offer_enabled'] = $best_offer_enabled;

        return $this;
    }

    /**
     * Gets best_offer_auto_accept_cents
     *
     * @return float|null
     */
    public function getBestOfferAutoAcceptCents()
    {
        return $this->container['best_offer_auto_accept_cents'];
    }

    /**
     * Sets best_offer_auto_accept_cents
     *
     * @param float|null $best_offer_auto_accept_cents best_offer_auto_accept_cents
     *
     * @return self
     */
    public function setBestOfferAutoAcceptCents($best_offer_auto_accept_cents)
    {
        $this->container['best_offer_auto_accept_cents'] = $best_offer_auto_accept_cents;

        return $this;
    }

    /**
     * Gets best_offer_auto_decline_cents
     *
     * @return float|null
     */
    public function getBestOfferAutoDeclineCents()
    {
        return $this->container['best_offer_auto_decline_cents'];
    }

    /**
     * Sets best_offer_auto_decline_cents
     *
     * @param float|null $best_offer_auto_decline_cents best_offer_auto_decline_cents
     *
     * @return self
     */
    public function setBestOfferAutoDeclineCents($best_offer_auto_decline_cents)
    {
        $this->container['best_offer_auto_decline_cents'] = $best_offer_auto_decline_cents;

        return $this;
    }

    /**
     * Gets aesthetic_tags
     *
     * @return string[]|null
     */
    public function getAestheticTags()
    {
        return $this->container['aesthetic_tags'];
    }

    /**
     * Sets aesthetic_tags
     *
     * @param string[]|null $aesthetic_tags aesthetic_tags
     *
     * @return self
     */
    public function setAestheticTags($aesthetic_tags)
    {
        $this->container['aesthetic_tags'] = $aesthetic_tags;

        return $this;
    }

    /**
     * Gets allows_local_pickup
     *
     * @return bool
     */
    public function getAllowsLocalPickup()
    {
        return $this->container['allows_local_pickup'];
    }

    /**
     * Sets allows_local_pickup
     *
     * @param bool $allows_local_pickup allows_local_pickup
     *
     * @return self
     */
    public function setAllowsLocalPickup($allows_local_pickup)
    {
        $this->container['allows_local_pickup'] = $allows_local_pickup;

        return $this;
    }

    /**
     * Gets pickup_radius_miles
     *
     * @return float|null
     */
    public function getPickupRadiusMiles()
    {
        return $this->container['pickup_radius_miles'];
    }

    /**
     * Sets pickup_radius_miles
     *
     * @param float|null $pickup_radius_miles pickup_radius_miles
     *
     * @return self
     */
    public function setPickupRadiusMiles($pickup_radius_miles)
    {
        $this->container['pickup_radius_miles'] = $pickup_radius_miles;

        return $this;
    }

    /**
     * Gets pickup_lat
     *
     * @return string|null
     */
    public function getPickupLat()
    {
        return $this->container['pickup_lat'];
    }

    /**
     * Sets pickup_lat
     *
     * @param string|null $pickup_lat pickup_lat
     *
     * @return self
     */
    public function setPickupLat($pickup_lat)
    {
        $this->container['pickup_lat'] = $pickup_lat;

        return $this;
    }

    /**
     * Gets pickup_lng
     *
     * @return string|null
     */
    public function getPickupLng()
    {
        return $this->container['pickup_lng'];
    }

    /**
     * Sets pickup_lng
     *
     * @param string|null $pickup_lng pickup_lng
     *
     * @return self
     */
    public function setPickupLng($pickup_lng)
    {
        $this->container['pickup_lng'] = $pickup_lng;

        return $this;
    }

    /**
     * Gets refurbished_tier
     *
     * @return string|null
     */
    public function getRefurbishedTier()
    {
        return $this->container['refurbished_tier'];
    }

    /**
     * Sets refurbished_tier
     *
     * @param string|null $refurbished_tier refurbished_tier
     *
     * @return self
     */
    public function setRefurbishedTier($refurbished_tier)
    {
        $this->container['refurbished_tier'] = $refurbished_tier;

        return $this;
    }

    /**
     * Gets charity_slug
     *
     * @return string|null
     */
    public function getCharitySlug()
    {
        return $this->container['charity_slug'];
    }

    /**
     * Sets charity_slug
     *
     * @param string|null $charity_slug charity_slug
     *
     * @return self
     */
    public function setCharitySlug($charity_slug)
    {
        $this->container['charity_slug'] = $charity_slug;

        return $this;
    }

    /**
     * Gets charity_percent_bps
     *
     * @return float|null
     */
    public function getCharityPercentBps()
    {
        return $this->container['charity_percent_bps'];
    }

    /**
     * Sets charity_percent_bps
     *
     * @param float|null $charity_percent_bps charity_percent_bps
     *
     * @return self
     */
    public function setCharityPercentBps($charity_percent_bps)
    {
        $this->container['charity_percent_bps'] = $charity_percent_bps;

        return $this;
    }

    /**
     * Gets crossly_return_policy_id
     *
     * @return string|null
     */
    public function getCrosslyReturnPolicyId()
    {
        return $this->container['crossly_return_policy_id'];
    }

    /**
     * Sets crossly_return_policy_id
     *
     * @param string|null $crossly_return_policy_id crossly_return_policy_id
     *
     * @return self
     */
    public function setCrosslyReturnPolicyId($crossly_return_policy_id)
    {
        $this->container['crossly_return_policy_id'] = $crossly_return_policy_id;

        return $this;
    }

    /**
     * Gets crossly_shipping_policy_id
     *
     * @return string|null
     */
    public function getCrosslyShippingPolicyId()
    {
        return $this->container['crossly_shipping_policy_id'];
    }

    /**
     * Sets crossly_shipping_policy_id
     *
     * @param string|null $crossly_shipping_policy_id crossly_shipping_policy_id
     *
     * @return self
     */
    public function setCrosslyShippingPolicyId($crossly_shipping_policy_id)
    {
        $this->container['crossly_shipping_policy_id'] = $crossly_shipping_policy_id;

        return $this;
    }

    /**
     * Gets crossly_payment_policy_id
     *
     * @return string|null
     */
    public function getCrosslyPaymentPolicyId()
    {
        return $this->container['crossly_payment_policy_id'];
    }

    /**
     * Sets crossly_payment_policy_id
     *
     * @param string|null $crossly_payment_policy_id crossly_payment_policy_id
     *
     * @return self
     */
    public function setCrosslyPaymentPolicyId($crossly_payment_policy_id)
    {
        $this->container['crossly_payment_policy_id'] = $crossly_payment_policy_id;

        return $this;
    }

    /**
     * Gets retail_price_cents
     *
     * @return float|null
     */
    public function getRetailPriceCents()
    {
        return $this->container['retail_price_cents'];
    }

    /**
     * Sets retail_price_cents
     *
     * @param float|null $retail_price_cents retail_price_cents
     *
     * @return self
     */
    public function setRetailPriceCents($retail_price_cents)
    {
        $this->container['retail_price_cents'] = $retail_price_cents;

        return $this;
    }

    /**
     * Gets restricted_countries
     *
     * @return string[]|null
     */
    public function getRestrictedCountries()
    {
        return $this->container['restricted_countries'];
    }

    /**
     * Sets restricted_countries
     *
     * @param string[]|null $restricted_countries restricted_countries
     *
     * @return self
     */
    public function setRestrictedCountries($restricted_countries)
    {
        $this->container['restricted_countries'] = $restricted_countries;

        return $this;
    }

    /**
     * Gets auction_extend_seconds
     *
     * @return float|null
     */
    public function getAuctionExtendSeconds()
    {
        return $this->container['auction_extend_seconds'];
    }

    /**
     * Sets auction_extend_seconds
     *
     * @param float|null $auction_extend_seconds auction_extend_seconds
     *
     * @return self
     */
    public function setAuctionExtendSeconds($auction_extend_seconds)
    {
        $this->container['auction_extend_seconds'] = $auction_extend_seconds;

        return $this;
    }

    /**
     * Gets authentication_provider_slug
     *
     * @return string|null
     */
    public function getAuthenticationProviderSlug()
    {
        return $this->container['authentication_provider_slug'];
    }

    /**
     * Sets authentication_provider_slug
     *
     * @param string|null $authentication_provider_slug authentication_provider_slug
     *
     * @return self
     */
    public function setAuthenticationProviderSlug($authentication_provider_slug)
    {
        $this->container['authentication_provider_slug'] = $authentication_provider_slug;

        return $this;
    }

    /**
     * Gets authentication_required
     *
     * @return bool
     */
    public function getAuthenticationRequired()
    {
        return $this->container['authentication_required'];
    }

    /**
     * Sets authentication_required
     *
     * @param bool $authentication_required authentication_required
     *
     * @return self
     */
    public function setAuthenticationRequired($authentication_required)
    {
        $this->container['authentication_required'] = $authentication_required;

        return $this;
    }

    /**
     * Gets has_variants
     *
     * @return bool
     */
    public function getHasVariants()
    {
        return $this->container['has_variants'];
    }

    /**
     * Sets has_variants
     *
     * @param bool $has_variants has_variants
     *
     * @return self
     */
    public function setHasVariants($has_variants)
    {
        $this->container['has_variants'] = $has_variants;

        return $this;
    }

    /**
     * Gets charity_id
     *
     * @return string|null
     */
    public function getCharityId()
    {
        return $this->container['charity_id'];
    }

    /**
     * Sets charity_id
     *
     * @param string|null $charity_id charity_id
     *
     * @return self
     */
    public function setCharityId($charity_id)
    {
        $this->container['charity_id'] = $charity_id;

        return $this;
    }

    /**
     * Gets min_order_quantity
     *
     * @return float
     */
    public function getMinOrderQuantity()
    {
        return $this->container['min_order_quantity'];
    }

    /**
     * Sets min_order_quantity
     *
     * @param float $min_order_quantity min_order_quantity
     *
     * @return self
     */
    public function setMinOrderQuantity($min_order_quantity)
    {
        $this->container['min_order_quantity'] = $min_order_quantity;

        return $this;
    }

    /**
     * Gets wholesale_unit_price_cents
     *
     * @return float|null
     */
    public function getWholesaleUnitPriceCents()
    {
        return $this->container['wholesale_unit_price_cents'];
    }

    /**
     * Sets wholesale_unit_price_cents
     *
     * @param float|null $wholesale_unit_price_cents wholesale_unit_price_cents
     *
     * @return self
     */
    public function setWholesaleUnitPriceCents($wholesale_unit_price_cents)
    {
        $this->container['wholesale_unit_price_cents'] = $wholesale_unit_price_cents;

        return $this;
    }

    /**
     * Gets wholesale_min_quantity
     *
     * @return float|null
     */
    public function getWholesaleMinQuantity()
    {
        return $this->container['wholesale_min_quantity'];
    }

    /**
     * Sets wholesale_min_quantity
     *
     * @param float|null $wholesale_min_quantity wholesale_min_quantity
     *
     * @return self
     */
    public function setWholesaleMinQuantity($wholesale_min_quantity)
    {
        $this->container['wholesale_min_quantity'] = $wholesale_min_quantity;

        return $this;
    }

    /**
     * Gets auction_reserve_cents
     *
     * @return float|null
     */
    public function getAuctionReserveCents()
    {
        return $this->container['auction_reserve_cents'];
    }

    /**
     * Sets auction_reserve_cents
     *
     * @param float|null $auction_reserve_cents auction_reserve_cents
     *
     * @return self
     */
    public function setAuctionReserveCents($auction_reserve_cents)
    {
        $this->container['auction_reserve_cents'] = $auction_reserve_cents;

        return $this;
    }

    /**
     * Gets is_gtc
     *
     * @return bool
     */
    public function getIsGtc()
    {
        return $this->container['is_gtc'];
    }

    /**
     * Sets is_gtc
     *
     * @param bool $is_gtc is_gtc
     *
     * @return self
     */
    public function setIsGtc($is_gtc)
    {
        $this->container['is_gtc'] = $is_gtc;

        return $this;
    }

    /**
     * Gets handling_time_days
     *
     * @return float
     */
    public function getHandlingTimeDays()
    {
        return $this->container['handling_time_days'];
    }

    /**
     * Sets handling_time_days
     *
     * @param float $handling_time_days handling_time_days
     *
     * @return self
     */
    public function setHandlingTimeDays($handling_time_days)
    {
        $this->container['handling_time_days'] = $handling_time_days;

        return $this;
    }

    /**
     * Gets item_location
     *
     * @return string|null
     */
    public function getItemLocation()
    {
        return $this->container['item_location'];
    }

    /**
     * Sets item_location
     *
     * @param string|null $item_location item_location
     *
     * @return self
     */
    public function setItemLocation($item_location)
    {
        $this->container['item_location'] = $item_location;

        return $this;
    }

    /**
     * Gets item_location_zip
     *
     * @return string|null
     */
    public function getItemLocationZip()
    {
        return $this->container['item_location_zip'];
    }

    /**
     * Sets item_location_zip
     *
     * @param string|null $item_location_zip item_location_zip
     *
     * @return self
     */
    public function setItemLocationZip($item_location_zip)
    {
        $this->container['item_location_zip'] = $item_location_zip;

        return $this;
    }

    /**
     * Gets item_location_country
     *
     * @return string|null
     */
    public function getItemLocationCountry()
    {
        return $this->container['item_location_country'];
    }

    /**
     * Sets item_location_country
     *
     * @param string|null $item_location_country item_location_country
     *
     * @return self
     */
    public function setItemLocationCountry($item_location_country)
    {
        $this->container['item_location_country'] = $item_location_country;

        return $this;
    }

    /**
     * Gets declared_shipping_cost
     *
     * @return string|null
     */
    public function getDeclaredShippingCost()
    {
        return $this->container['declared_shipping_cost'];
    }

    /**
     * Sets declared_shipping_cost
     *
     * @param string|null $declared_shipping_cost declared_shipping_cost
     *
     * @return self
     */
    public function setDeclaredShippingCost($declared_shipping_cost)
    {
        $this->container['declared_shipping_cost'] = $declared_shipping_cost;

        return $this;
    }

    /**
     * Gets return_policy_text
     *
     * @return string|null
     */
    public function getReturnPolicyText()
    {
        return $this->container['return_policy_text'];
    }

    /**
     * Sets return_policy_text
     *
     * @param string|null $return_policy_text return_policy_text
     *
     * @return self
     */
    public function setReturnPolicyText($return_policy_text)
    {
        $this->container['return_policy_text'] = $return_policy_text;

        return $this;
    }

    /**
     * Gets last_drift_checked_at
     *
     * @return \DateTime|null
     */
    public function getLastDriftCheckedAt()
    {
        return $this->container['last_drift_checked_at'];
    }

    /**
     * Sets last_drift_checked_at
     *
     * @param \DateTime|null $last_drift_checked_at last_drift_checked_at
     *
     * @return self
     */
    public function setLastDriftCheckedAt($last_drift_checked_at)
    {
        $this->container['last_drift_checked_at'] = $last_drift_checked_at;

        return $this;
    }

    /**
     * Gets verification_failed
     *
     * @return bool
     */
    public function getVerificationFailed()
    {
        return $this->container['verification_failed'];
    }

    /**
     * Sets verification_failed
     *
     * @param bool $verification_failed verification_failed
     *
     * @return self
     */
    public function setVerificationFailed($verification_failed)
    {
        $this->container['verification_failed'] = $verification_failed;

        return $this;
    }

    /**
     * Gets published_overrides
     *
     * @return object|null
     */
    public function getPublishedOverrides()
    {
        return $this->container['published_overrides'];
    }

    /**
     * Sets published_overrides
     *
     * @param object|null $published_overrides published_overrides
     *
     * @return self
     */
    public function setPublishedOverrides($published_overrides)
    {
        $this->container['published_overrides'] = $published_overrides;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


