<?php
/**
 * GetMarketProductResponseVariants
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Model;

use \ArrayAccess;
use \Crossly\ObjectSerializer;

/**
 * GetMarketProductResponseVariants Class Doc Comment
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class GetMarketProductResponseVariants implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetMarketProductResponse_variants';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'label' => 'string',
        'sort_key' => 'float',
        'external_id' => 'string',
        'external_source' => 'string',
        'external_synced_at' => '\DateTime',
        'last_sale_cents' => 'float',
        'trades_count' => 'float',
        'sku_id' => 'string',
        'last_sale_at' => '\DateTime',
        'best_bid_cents' => 'float',
        'best_ask_cents' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'label' => null,
        'sort_key' => null,
        'external_id' => null,
        'external_source' => null,
        'external_synced_at' => 'date-time',
        'last_sale_cents' => null,
        'trades_count' => null,
        'sku_id' => null,
        'last_sale_at' => 'date-time',
        'best_bid_cents' => null,
        'best_ask_cents' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'label' => 'label',
        'sort_key' => 'sortKey',
        'external_id' => 'externalId',
        'external_source' => 'externalSource',
        'external_synced_at' => 'externalSyncedAt',
        'last_sale_cents' => 'lastSaleCents',
        'trades_count' => 'tradesCount',
        'sku_id' => 'skuId',
        'last_sale_at' => 'lastSaleAt',
        'best_bid_cents' => 'bestBidCents',
        'best_ask_cents' => 'bestAskCents'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'label' => 'setLabel',
        'sort_key' => 'setSortKey',
        'external_id' => 'setExternalId',
        'external_source' => 'setExternalSource',
        'external_synced_at' => 'setExternalSyncedAt',
        'last_sale_cents' => 'setLastSaleCents',
        'trades_count' => 'setTradesCount',
        'sku_id' => 'setSkuId',
        'last_sale_at' => 'setLastSaleAt',
        'best_bid_cents' => 'setBestBidCents',
        'best_ask_cents' => 'setBestAskCents'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'label' => 'getLabel',
        'sort_key' => 'getSortKey',
        'external_id' => 'getExternalId',
        'external_source' => 'getExternalSource',
        'external_synced_at' => 'getExternalSyncedAt',
        'last_sale_cents' => 'getLastSaleCents',
        'trades_count' => 'getTradesCount',
        'sku_id' => 'getSkuId',
        'last_sale_at' => 'getLastSaleAt',
        'best_bid_cents' => 'getBestBidCents',
        'best_ask_cents' => 'getBestAskCents'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['label'] = $data['label'] ?? null;
        $this->container['sort_key'] = $data['sort_key'] ?? null;
        $this->container['external_id'] = $data['external_id'] ?? null;
        $this->container['external_source'] = $data['external_source'] ?? null;
        $this->container['external_synced_at'] = $data['external_synced_at'] ?? null;
        $this->container['last_sale_cents'] = $data['last_sale_cents'] ?? null;
        $this->container['trades_count'] = $data['trades_count'] ?? null;
        $this->container['sku_id'] = $data['sku_id'] ?? null;
        $this->container['last_sale_at'] = $data['last_sale_at'] ?? null;
        $this->container['best_bid_cents'] = $data['best_bid_cents'] ?? null;
        $this->container['best_ask_cents'] = $data['best_ask_cents'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['label'] === null) {
            $invalidProperties[] = "'label' can't be null";
        }
        if ($this->container['sort_key'] === null) {
            $invalidProperties[] = "'sort_key' can't be null";
        }
        if ($this->container['trades_count'] === null) {
            $invalidProperties[] = "'trades_count' can't be null";
        }
        if ($this->container['sku_id'] === null) {
            $invalidProperties[] = "'sku_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string $label label
     *
     * @return self
     */
    public function setLabel($label)
    {
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets sort_key
     *
     * @return float
     */
    public function getSortKey()
    {
        return $this->container['sort_key'];
    }

    /**
     * Sets sort_key
     *
     * @param float $sort_key sort_key
     *
     * @return self
     */
    public function setSortKey($sort_key)
    {
        $this->container['sort_key'] = $sort_key;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id external_id
     *
     * @return self
     */
    public function setExternalId($external_id)
    {
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets external_source
     *
     * @return string|null
     */
    public function getExternalSource()
    {
        return $this->container['external_source'];
    }

    /**
     * Sets external_source
     *
     * @param string|null $external_source external_source
     *
     * @return self
     */
    public function setExternalSource($external_source)
    {
        $this->container['external_source'] = $external_source;

        return $this;
    }

    /**
     * Gets external_synced_at
     *
     * @return \DateTime|null
     */
    public function getExternalSyncedAt()
    {
        return $this->container['external_synced_at'];
    }

    /**
     * Sets external_synced_at
     *
     * @param \DateTime|null $external_synced_at external_synced_at
     *
     * @return self
     */
    public function setExternalSyncedAt($external_synced_at)
    {
        $this->container['external_synced_at'] = $external_synced_at;

        return $this;
    }

    /**
     * Gets last_sale_cents
     *
     * @return float|null
     */
    public function getLastSaleCents()
    {
        return $this->container['last_sale_cents'];
    }

    /**
     * Sets last_sale_cents
     *
     * @param float|null $last_sale_cents last_sale_cents
     *
     * @return self
     */
    public function setLastSaleCents($last_sale_cents)
    {
        $this->container['last_sale_cents'] = $last_sale_cents;

        return $this;
    }

    /**
     * Gets trades_count
     *
     * @return float
     */
    public function getTradesCount()
    {
        return $this->container['trades_count'];
    }

    /**
     * Sets trades_count
     *
     * @param float $trades_count trades_count
     *
     * @return self
     */
    public function setTradesCount($trades_count)
    {
        $this->container['trades_count'] = $trades_count;

        return $this;
    }

    /**
     * Gets sku_id
     *
     * @return string
     */
    public function getSkuId()
    {
        return $this->container['sku_id'];
    }

    /**
     * Sets sku_id
     *
     * @param string $sku_id sku_id
     *
     * @return self
     */
    public function setSkuId($sku_id)
    {
        $this->container['sku_id'] = $sku_id;

        return $this;
    }

    /**
     * Gets last_sale_at
     *
     * @return \DateTime|null
     */
    public function getLastSaleAt()
    {
        return $this->container['last_sale_at'];
    }

    /**
     * Sets last_sale_at
     *
     * @param \DateTime|null $last_sale_at last_sale_at
     *
     * @return self
     */
    public function setLastSaleAt($last_sale_at)
    {
        $this->container['last_sale_at'] = $last_sale_at;

        return $this;
    }

    /**
     * Gets best_bid_cents
     *
     * @return float|null
     */
    public function getBestBidCents()
    {
        return $this->container['best_bid_cents'];
    }

    /**
     * Sets best_bid_cents
     *
     * @param float|null $best_bid_cents best_bid_cents
     *
     * @return self
     */
    public function setBestBidCents($best_bid_cents)
    {
        $this->container['best_bid_cents'] = $best_bid_cents;

        return $this;
    }

    /**
     * Gets best_ask_cents
     *
     * @return float|null
     */
    public function getBestAskCents()
    {
        return $this->container['best_ask_cents'];
    }

    /**
     * Sets best_ask_cents
     *
     * @param float|null $best_ask_cents best_ask_cents
     *
     * @return self
     */
    public function setBestAskCents($best_ask_cents)
    {
        $this->container['best_ask_cents'] = $best_ask_cents;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


