<?php
/**
 * GetMarketProductResponseProduct
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Model;

use \ArrayAccess;
use \Crossly\ObjectSerializer;

/**
 * GetMarketProductResponseProduct Class Doc Comment
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class GetMarketProductResponseProduct implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetMarketProductResponse_product';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'brand' => 'string',
        'name' => 'string',
        'created_at' => '\DateTime',
        'status' => 'string',
        'retail_cents' => 'float',
        'category_slug' => 'string',
        'external_id' => 'string',
        'image_url' => 'string',
        'model' => 'string',
        'colorway' => 'string',
        'style_code' => 'string',
        'release_date' => 'string',
        'submitted_by_user_id' => 'string',
        'approved_by_user_id' => 'string',
        'approved_at' => '\DateTime',
        'rejection_reason' => 'string',
        'proposed_variants' => '\Crossly\Model\GetMarketProductResponseProductProposedVariants[]',
        'verification' => 'object',
        'ai_verdict' => 'object',
        'submission_source' => 'string',
        'duplicate_of_sku_id' => 'string',
        'preferred_provider_slug' => 'string',
        'allow_pre_bid' => 'bool',
        'pre_bid_opens_at' => '\DateTime',
        'featured' => 'bool',
        'external_source' => 'string',
        'external_synced_at' => '\DateTime',
        'graded_grade_keys' => 'string[]',
        'lowest_ask_cents' => 'float',
        'highest_bid_cents' => 'float',
        'last_sale_cents' => 'float',
        'trades_count' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'brand' => null,
        'name' => null,
        'created_at' => 'date-time',
        'status' => null,
        'retail_cents' => null,
        'category_slug' => null,
        'external_id' => null,
        'image_url' => null,
        'model' => null,
        'colorway' => null,
        'style_code' => null,
        'release_date' => null,
        'submitted_by_user_id' => null,
        'approved_by_user_id' => null,
        'approved_at' => 'date-time',
        'rejection_reason' => null,
        'proposed_variants' => null,
        'verification' => null,
        'ai_verdict' => null,
        'submission_source' => null,
        'duplicate_of_sku_id' => null,
        'preferred_provider_slug' => null,
        'allow_pre_bid' => null,
        'pre_bid_opens_at' => 'date-time',
        'featured' => null,
        'external_source' => null,
        'external_synced_at' => 'date-time',
        'graded_grade_keys' => null,
        'lowest_ask_cents' => null,
        'highest_bid_cents' => null,
        'last_sale_cents' => null,
        'trades_count' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'brand' => 'brand',
        'name' => 'name',
        'created_at' => 'createdAt',
        'status' => 'status',
        'retail_cents' => 'retailCents',
        'category_slug' => 'categorySlug',
        'external_id' => 'externalId',
        'image_url' => 'imageUrl',
        'model' => 'model',
        'colorway' => 'colorway',
        'style_code' => 'styleCode',
        'release_date' => 'releaseDate',
        'submitted_by_user_id' => 'submittedByUserId',
        'approved_by_user_id' => 'approvedByUserId',
        'approved_at' => 'approvedAt',
        'rejection_reason' => 'rejectionReason',
        'proposed_variants' => 'proposedVariants',
        'verification' => 'verification',
        'ai_verdict' => 'aiVerdict',
        'submission_source' => 'submissionSource',
        'duplicate_of_sku_id' => 'duplicateOfSkuId',
        'preferred_provider_slug' => 'preferredProviderSlug',
        'allow_pre_bid' => 'allowPreBid',
        'pre_bid_opens_at' => 'preBidOpensAt',
        'featured' => 'featured',
        'external_source' => 'externalSource',
        'external_synced_at' => 'externalSyncedAt',
        'graded_grade_keys' => 'gradedGradeKeys',
        'lowest_ask_cents' => 'lowestAskCents',
        'highest_bid_cents' => 'highestBidCents',
        'last_sale_cents' => 'lastSaleCents',
        'trades_count' => 'tradesCount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'brand' => 'setBrand',
        'name' => 'setName',
        'created_at' => 'setCreatedAt',
        'status' => 'setStatus',
        'retail_cents' => 'setRetailCents',
        'category_slug' => 'setCategorySlug',
        'external_id' => 'setExternalId',
        'image_url' => 'setImageUrl',
        'model' => 'setModel',
        'colorway' => 'setColorway',
        'style_code' => 'setStyleCode',
        'release_date' => 'setReleaseDate',
        'submitted_by_user_id' => 'setSubmittedByUserId',
        'approved_by_user_id' => 'setApprovedByUserId',
        'approved_at' => 'setApprovedAt',
        'rejection_reason' => 'setRejectionReason',
        'proposed_variants' => 'setProposedVariants',
        'verification' => 'setVerification',
        'ai_verdict' => 'setAiVerdict',
        'submission_source' => 'setSubmissionSource',
        'duplicate_of_sku_id' => 'setDuplicateOfSkuId',
        'preferred_provider_slug' => 'setPreferredProviderSlug',
        'allow_pre_bid' => 'setAllowPreBid',
        'pre_bid_opens_at' => 'setPreBidOpensAt',
        'featured' => 'setFeatured',
        'external_source' => 'setExternalSource',
        'external_synced_at' => 'setExternalSyncedAt',
        'graded_grade_keys' => 'setGradedGradeKeys',
        'lowest_ask_cents' => 'setLowestAskCents',
        'highest_bid_cents' => 'setHighestBidCents',
        'last_sale_cents' => 'setLastSaleCents',
        'trades_count' => 'setTradesCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'brand' => 'getBrand',
        'name' => 'getName',
        'created_at' => 'getCreatedAt',
        'status' => 'getStatus',
        'retail_cents' => 'getRetailCents',
        'category_slug' => 'getCategorySlug',
        'external_id' => 'getExternalId',
        'image_url' => 'getImageUrl',
        'model' => 'getModel',
        'colorway' => 'getColorway',
        'style_code' => 'getStyleCode',
        'release_date' => 'getReleaseDate',
        'submitted_by_user_id' => 'getSubmittedByUserId',
        'approved_by_user_id' => 'getApprovedByUserId',
        'approved_at' => 'getApprovedAt',
        'rejection_reason' => 'getRejectionReason',
        'proposed_variants' => 'getProposedVariants',
        'verification' => 'getVerification',
        'ai_verdict' => 'getAiVerdict',
        'submission_source' => 'getSubmissionSource',
        'duplicate_of_sku_id' => 'getDuplicateOfSkuId',
        'preferred_provider_slug' => 'getPreferredProviderSlug',
        'allow_pre_bid' => 'getAllowPreBid',
        'pre_bid_opens_at' => 'getPreBidOpensAt',
        'featured' => 'getFeatured',
        'external_source' => 'getExternalSource',
        'external_synced_at' => 'getExternalSyncedAt',
        'graded_grade_keys' => 'getGradedGradeKeys',
        'lowest_ask_cents' => 'getLowestAskCents',
        'highest_bid_cents' => 'getHighestBidCents',
        'last_sale_cents' => 'getLastSaleCents',
        'trades_count' => 'getTradesCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['brand'] = $data['brand'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['created_at'] = $data['created_at'] ?? null;
        $this->container['status'] = $data['status'] ?? null;
        $this->container['retail_cents'] = $data['retail_cents'] ?? null;
        $this->container['category_slug'] = $data['category_slug'] ?? null;
        $this->container['external_id'] = $data['external_id'] ?? null;
        $this->container['image_url'] = $data['image_url'] ?? null;
        $this->container['model'] = $data['model'] ?? null;
        $this->container['colorway'] = $data['colorway'] ?? null;
        $this->container['style_code'] = $data['style_code'] ?? null;
        $this->container['release_date'] = $data['release_date'] ?? null;
        $this->container['submitted_by_user_id'] = $data['submitted_by_user_id'] ?? null;
        $this->container['approved_by_user_id'] = $data['approved_by_user_id'] ?? null;
        $this->container['approved_at'] = $data['approved_at'] ?? null;
        $this->container['rejection_reason'] = $data['rejection_reason'] ?? null;
        $this->container['proposed_variants'] = $data['proposed_variants'] ?? null;
        $this->container['verification'] = $data['verification'] ?? null;
        $this->container['ai_verdict'] = $data['ai_verdict'] ?? null;
        $this->container['submission_source'] = $data['submission_source'] ?? null;
        $this->container['duplicate_of_sku_id'] = $data['duplicate_of_sku_id'] ?? null;
        $this->container['preferred_provider_slug'] = $data['preferred_provider_slug'] ?? null;
        $this->container['allow_pre_bid'] = $data['allow_pre_bid'] ?? null;
        $this->container['pre_bid_opens_at'] = $data['pre_bid_opens_at'] ?? null;
        $this->container['featured'] = $data['featured'] ?? null;
        $this->container['external_source'] = $data['external_source'] ?? null;
        $this->container['external_synced_at'] = $data['external_synced_at'] ?? null;
        $this->container['graded_grade_keys'] = $data['graded_grade_keys'] ?? null;
        $this->container['lowest_ask_cents'] = $data['lowest_ask_cents'] ?? null;
        $this->container['highest_bid_cents'] = $data['highest_bid_cents'] ?? null;
        $this->container['last_sale_cents'] = $data['last_sale_cents'] ?? null;
        $this->container['trades_count'] = $data['trades_count'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['category_slug'] === null) {
            $invalidProperties[] = "'category_slug' can't be null";
        }
        if ($this->container['proposed_variants'] === null) {
            $invalidProperties[] = "'proposed_variants' can't be null";
        }
        if ($this->container['verification'] === null) {
            $invalidProperties[] = "'verification' can't be null";
        }
        if ($this->container['allow_pre_bid'] === null) {
            $invalidProperties[] = "'allow_pre_bid' can't be null";
        }
        if ($this->container['featured'] === null) {
            $invalidProperties[] = "'featured' can't be null";
        }
        if ($this->container['graded_grade_keys'] === null) {
            $invalidProperties[] = "'graded_grade_keys' can't be null";
        }
        if ($this->container['trades_count'] === null) {
            $invalidProperties[] = "'trades_count' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets brand
     *
     * @return string|null
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     *
     * @param string|null $brand brand
     *
     * @return self
     */
    public function setBrand($brand)
    {
        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets retail_cents
     *
     * @return float|null
     */
    public function getRetailCents()
    {
        return $this->container['retail_cents'];
    }

    /**
     * Sets retail_cents
     *
     * @param float|null $retail_cents retail_cents
     *
     * @return self
     */
    public function setRetailCents($retail_cents)
    {
        $this->container['retail_cents'] = $retail_cents;

        return $this;
    }

    /**
     * Gets category_slug
     *
     * @return string
     */
    public function getCategorySlug()
    {
        return $this->container['category_slug'];
    }

    /**
     * Sets category_slug
     *
     * @param string $category_slug category_slug
     *
     * @return self
     */
    public function setCategorySlug($category_slug)
    {
        $this->container['category_slug'] = $category_slug;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id external_id
     *
     * @return self
     */
    public function setExternalId($external_id)
    {
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string|null
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string|null $image_url image_url
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets model
     *
     * @return string|null
     */
    public function getModel()
    {
        return $this->container['model'];
    }

    /**
     * Sets model
     *
     * @param string|null $model model
     *
     * @return self
     */
    public function setModel($model)
    {
        $this->container['model'] = $model;

        return $this;
    }

    /**
     * Gets colorway
     *
     * @return string|null
     */
    public function getColorway()
    {
        return $this->container['colorway'];
    }

    /**
     * Sets colorway
     *
     * @param string|null $colorway colorway
     *
     * @return self
     */
    public function setColorway($colorway)
    {
        $this->container['colorway'] = $colorway;

        return $this;
    }

    /**
     * Gets style_code
     *
     * @return string|null
     */
    public function getStyleCode()
    {
        return $this->container['style_code'];
    }

    /**
     * Sets style_code
     *
     * @param string|null $style_code style_code
     *
     * @return self
     */
    public function setStyleCode($style_code)
    {
        $this->container['style_code'] = $style_code;

        return $this;
    }

    /**
     * Gets release_date
     *
     * @return string|null
     */
    public function getReleaseDate()
    {
        return $this->container['release_date'];
    }

    /**
     * Sets release_date
     *
     * @param string|null $release_date release_date
     *
     * @return self
     */
    public function setReleaseDate($release_date)
    {
        $this->container['release_date'] = $release_date;

        return $this;
    }

    /**
     * Gets submitted_by_user_id
     *
     * @return string|null
     */
    public function getSubmittedByUserId()
    {
        return $this->container['submitted_by_user_id'];
    }

    /**
     * Sets submitted_by_user_id
     *
     * @param string|null $submitted_by_user_id submitted_by_user_id
     *
     * @return self
     */
    public function setSubmittedByUserId($submitted_by_user_id)
    {
        $this->container['submitted_by_user_id'] = $submitted_by_user_id;

        return $this;
    }

    /**
     * Gets approved_by_user_id
     *
     * @return string|null
     */
    public function getApprovedByUserId()
    {
        return $this->container['approved_by_user_id'];
    }

    /**
     * Sets approved_by_user_id
     *
     * @param string|null $approved_by_user_id approved_by_user_id
     *
     * @return self
     */
    public function setApprovedByUserId($approved_by_user_id)
    {
        $this->container['approved_by_user_id'] = $approved_by_user_id;

        return $this;
    }

    /**
     * Gets approved_at
     *
     * @return \DateTime|null
     */
    public function getApprovedAt()
    {
        return $this->container['approved_at'];
    }

    /**
     * Sets approved_at
     *
     * @param \DateTime|null $approved_at approved_at
     *
     * @return self
     */
    public function setApprovedAt($approved_at)
    {
        $this->container['approved_at'] = $approved_at;

        return $this;
    }

    /**
     * Gets rejection_reason
     *
     * @return string|null
     */
    public function getRejectionReason()
    {
        return $this->container['rejection_reason'];
    }

    /**
     * Sets rejection_reason
     *
     * @param string|null $rejection_reason rejection_reason
     *
     * @return self
     */
    public function setRejectionReason($rejection_reason)
    {
        $this->container['rejection_reason'] = $rejection_reason;

        return $this;
    }

    /**
     * Gets proposed_variants
     *
     * @return \Crossly\Model\GetMarketProductResponseProductProposedVariants[]
     */
    public function getProposedVariants()
    {
        return $this->container['proposed_variants'];
    }

    /**
     * Sets proposed_variants
     *
     * @param \Crossly\Model\GetMarketProductResponseProductProposedVariants[] $proposed_variants proposed_variants
     *
     * @return self
     */
    public function setProposedVariants($proposed_variants)
    {
        $this->container['proposed_variants'] = $proposed_variants;

        return $this;
    }

    /**
     * Gets verification
     *
     * @return object
     */
    public function getVerification()
    {
        return $this->container['verification'];
    }

    /**
     * Sets verification
     *
     * @param object $verification verification
     *
     * @return self
     */
    public function setVerification($verification)
    {
        $this->container['verification'] = $verification;

        return $this;
    }

    /**
     * Gets ai_verdict
     *
     * @return object|null
     */
    public function getAiVerdict()
    {
        return $this->container['ai_verdict'];
    }

    /**
     * Sets ai_verdict
     *
     * @param object|null $ai_verdict ai_verdict
     *
     * @return self
     */
    public function setAiVerdict($ai_verdict)
    {
        $this->container['ai_verdict'] = $ai_verdict;

        return $this;
    }

    /**
     * Gets submission_source
     *
     * @return string|null
     */
    public function getSubmissionSource()
    {
        return $this->container['submission_source'];
    }

    /**
     * Sets submission_source
     *
     * @param string|null $submission_source submission_source
     *
     * @return self
     */
    public function setSubmissionSource($submission_source)
    {
        $this->container['submission_source'] = $submission_source;

        return $this;
    }

    /**
     * Gets duplicate_of_sku_id
     *
     * @return string|null
     */
    public function getDuplicateOfSkuId()
    {
        return $this->container['duplicate_of_sku_id'];
    }

    /**
     * Sets duplicate_of_sku_id
     *
     * @param string|null $duplicate_of_sku_id duplicate_of_sku_id
     *
     * @return self
     */
    public function setDuplicateOfSkuId($duplicate_of_sku_id)
    {
        $this->container['duplicate_of_sku_id'] = $duplicate_of_sku_id;

        return $this;
    }

    /**
     * Gets preferred_provider_slug
     *
     * @return string|null
     */
    public function getPreferredProviderSlug()
    {
        return $this->container['preferred_provider_slug'];
    }

    /**
     * Sets preferred_provider_slug
     *
     * @param string|null $preferred_provider_slug preferred_provider_slug
     *
     * @return self
     */
    public function setPreferredProviderSlug($preferred_provider_slug)
    {
        $this->container['preferred_provider_slug'] = $preferred_provider_slug;

        return $this;
    }

    /**
     * Gets allow_pre_bid
     *
     * @return bool
     */
    public function getAllowPreBid()
    {
        return $this->container['allow_pre_bid'];
    }

    /**
     * Sets allow_pre_bid
     *
     * @param bool $allow_pre_bid allow_pre_bid
     *
     * @return self
     */
    public function setAllowPreBid($allow_pre_bid)
    {
        $this->container['allow_pre_bid'] = $allow_pre_bid;

        return $this;
    }

    /**
     * Gets pre_bid_opens_at
     *
     * @return \DateTime|null
     */
    public function getPreBidOpensAt()
    {
        return $this->container['pre_bid_opens_at'];
    }

    /**
     * Sets pre_bid_opens_at
     *
     * @param \DateTime|null $pre_bid_opens_at pre_bid_opens_at
     *
     * @return self
     */
    public function setPreBidOpensAt($pre_bid_opens_at)
    {
        $this->container['pre_bid_opens_at'] = $pre_bid_opens_at;

        return $this;
    }

    /**
     * Gets featured
     *
     * @return bool
     */
    public function getFeatured()
    {
        return $this->container['featured'];
    }

    /**
     * Sets featured
     *
     * @param bool $featured featured
     *
     * @return self
     */
    public function setFeatured($featured)
    {
        $this->container['featured'] = $featured;

        return $this;
    }

    /**
     * Gets external_source
     *
     * @return string|null
     */
    public function getExternalSource()
    {
        return $this->container['external_source'];
    }

    /**
     * Sets external_source
     *
     * @param string|null $external_source external_source
     *
     * @return self
     */
    public function setExternalSource($external_source)
    {
        $this->container['external_source'] = $external_source;

        return $this;
    }

    /**
     * Gets external_synced_at
     *
     * @return \DateTime|null
     */
    public function getExternalSyncedAt()
    {
        return $this->container['external_synced_at'];
    }

    /**
     * Sets external_synced_at
     *
     * @param \DateTime|null $external_synced_at external_synced_at
     *
     * @return self
     */
    public function setExternalSyncedAt($external_synced_at)
    {
        $this->container['external_synced_at'] = $external_synced_at;

        return $this;
    }

    /**
     * Gets graded_grade_keys
     *
     * @return string[]
     */
    public function getGradedGradeKeys()
    {
        return $this->container['graded_grade_keys'];
    }

    /**
     * Sets graded_grade_keys
     *
     * @param string[] $graded_grade_keys graded_grade_keys
     *
     * @return self
     */
    public function setGradedGradeKeys($graded_grade_keys)
    {
        $this->container['graded_grade_keys'] = $graded_grade_keys;

        return $this;
    }

    /**
     * Gets lowest_ask_cents
     *
     * @return float|null
     */
    public function getLowestAskCents()
    {
        return $this->container['lowest_ask_cents'];
    }

    /**
     * Sets lowest_ask_cents
     *
     * @param float|null $lowest_ask_cents lowest_ask_cents
     *
     * @return self
     */
    public function setLowestAskCents($lowest_ask_cents)
    {
        $this->container['lowest_ask_cents'] = $lowest_ask_cents;

        return $this;
    }

    /**
     * Gets highest_bid_cents
     *
     * @return float|null
     */
    public function getHighestBidCents()
    {
        return $this->container['highest_bid_cents'];
    }

    /**
     * Sets highest_bid_cents
     *
     * @param float|null $highest_bid_cents highest_bid_cents
     *
     * @return self
     */
    public function setHighestBidCents($highest_bid_cents)
    {
        $this->container['highest_bid_cents'] = $highest_bid_cents;

        return $this;
    }

    /**
     * Gets last_sale_cents
     *
     * @return float|null
     */
    public function getLastSaleCents()
    {
        return $this->container['last_sale_cents'];
    }

    /**
     * Sets last_sale_cents
     *
     * @param float|null $last_sale_cents last_sale_cents
     *
     * @return self
     */
    public function setLastSaleCents($last_sale_cents)
    {
        $this->container['last_sale_cents'] = $last_sale_cents;

        return $this;
    }

    /**
     * Gets trades_count
     *
     * @return float
     */
    public function getTradesCount()
    {
        return $this->container['trades_count'];
    }

    /**
     * Sets trades_count
     *
     * @param float $trades_count trades_count
     *
     * @return self
     */
    public function setTradesCount($trades_count)
    {
        $this->container['trades_count'] = $trades_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


