<?php
/**
 * ListListingDiscrepanciesItem
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Model;

use \ArrayAccess;
use \Crossly\ObjectSerializer;

/**
 * ListListingDiscrepanciesItem Class Doc Comment
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ListListingDiscrepanciesItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ListListingDiscrepanciesItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'user_id' => 'string',
        'source' => 'string',
        'platform' => 'string',
        'listing_id' => 'string',
        'account_slot' => 'float',
        'last_error' => 'string',
        'field' => 'string',
        'our_value' => 'string',
        'remote_value' => 'string',
        'first_detected_at' => '\DateTime',
        'last_detected_at' => '\DateTime',
        'dismissed_at' => '\DateTime',
        'dismissed_remote_value' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'user_id' => null,
        'source' => null,
        'platform' => null,
        'listing_id' => null,
        'account_slot' => null,
        'last_error' => null,
        'field' => null,
        'our_value' => null,
        'remote_value' => null,
        'first_detected_at' => 'date-time',
        'last_detected_at' => 'date-time',
        'dismissed_at' => 'date-time',
        'dismissed_remote_value' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'user_id' => 'userId',
        'source' => 'source',
        'platform' => 'platform',
        'listing_id' => 'listingId',
        'account_slot' => 'accountSlot',
        'last_error' => 'lastError',
        'field' => 'field',
        'our_value' => 'ourValue',
        'remote_value' => 'remoteValue',
        'first_detected_at' => 'firstDetectedAt',
        'last_detected_at' => 'lastDetectedAt',
        'dismissed_at' => 'dismissedAt',
        'dismissed_remote_value' => 'dismissedRemoteValue'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'user_id' => 'setUserId',
        'source' => 'setSource',
        'platform' => 'setPlatform',
        'listing_id' => 'setListingId',
        'account_slot' => 'setAccountSlot',
        'last_error' => 'setLastError',
        'field' => 'setField',
        'our_value' => 'setOurValue',
        'remote_value' => 'setRemoteValue',
        'first_detected_at' => 'setFirstDetectedAt',
        'last_detected_at' => 'setLastDetectedAt',
        'dismissed_at' => 'setDismissedAt',
        'dismissed_remote_value' => 'setDismissedRemoteValue'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'user_id' => 'getUserId',
        'source' => 'getSource',
        'platform' => 'getPlatform',
        'listing_id' => 'getListingId',
        'account_slot' => 'getAccountSlot',
        'last_error' => 'getLastError',
        'field' => 'getField',
        'our_value' => 'getOurValue',
        'remote_value' => 'getRemoteValue',
        'first_detected_at' => 'getFirstDetectedAt',
        'last_detected_at' => 'getLastDetectedAt',
        'dismissed_at' => 'getDismissedAt',
        'dismissed_remote_value' => 'getDismissedRemoteValue'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['created_at'] = $data['created_at'] ?? null;
        $this->container['updated_at'] = $data['updated_at'] ?? null;
        $this->container['user_id'] = $data['user_id'] ?? null;
        $this->container['source'] = $data['source'] ?? null;
        $this->container['platform'] = $data['platform'] ?? null;
        $this->container['listing_id'] = $data['listing_id'] ?? null;
        $this->container['account_slot'] = $data['account_slot'] ?? null;
        $this->container['last_error'] = $data['last_error'] ?? null;
        $this->container['field'] = $data['field'] ?? null;
        $this->container['our_value'] = $data['our_value'] ?? null;
        $this->container['remote_value'] = $data['remote_value'] ?? null;
        $this->container['first_detected_at'] = $data['first_detected_at'] ?? null;
        $this->container['last_detected_at'] = $data['last_detected_at'] ?? null;
        $this->container['dismissed_at'] = $data['dismissed_at'] ?? null;
        $this->container['dismissed_remote_value'] = $data['dismissed_remote_value'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        if ($this->container['user_id'] === null) {
            $invalidProperties[] = "'user_id' can't be null";
        }
        if ($this->container['source'] === null) {
            $invalidProperties[] = "'source' can't be null";
        }
        if ($this->container['platform'] === null) {
            $invalidProperties[] = "'platform' can't be null";
        }
        if ($this->container['listing_id'] === null) {
            $invalidProperties[] = "'listing_id' can't be null";
        }
        if ($this->container['account_slot'] === null) {
            $invalidProperties[] = "'account_slot' can't be null";
        }
        if ($this->container['field'] === null) {
            $invalidProperties[] = "'field' can't be null";
        }
        if ($this->container['first_detected_at'] === null) {
            $invalidProperties[] = "'first_detected_at' can't be null";
        }
        if ($this->container['last_detected_at'] === null) {
            $invalidProperties[] = "'last_detected_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets platform
     *
     * @return string
     */
    public function getPlatform()
    {
        return $this->container['platform'];
    }

    /**
     * Sets platform
     *
     * @param string $platform platform
     *
     * @return self
     */
    public function setPlatform($platform)
    {
        $this->container['platform'] = $platform;

        return $this;
    }

    /**
     * Gets listing_id
     *
     * @return string
     */
    public function getListingId()
    {
        return $this->container['listing_id'];
    }

    /**
     * Sets listing_id
     *
     * @param string $listing_id listing_id
     *
     * @return self
     */
    public function setListingId($listing_id)
    {
        $this->container['listing_id'] = $listing_id;

        return $this;
    }

    /**
     * Gets account_slot
     *
     * @return float
     */
    public function getAccountSlot()
    {
        return $this->container['account_slot'];
    }

    /**
     * Sets account_slot
     *
     * @param float $account_slot account_slot
     *
     * @return self
     */
    public function setAccountSlot($account_slot)
    {
        $this->container['account_slot'] = $account_slot;

        return $this;
    }

    /**
     * Gets last_error
     *
     * @return string|null
     */
    public function getLastError()
    {
        return $this->container['last_error'];
    }

    /**
     * Sets last_error
     *
     * @param string|null $last_error last_error
     *
     * @return self
     */
    public function setLastError($last_error)
    {
        $this->container['last_error'] = $last_error;

        return $this;
    }

    /**
     * Gets field
     *
     * @return string
     */
    public function getField()
    {
        return $this->container['field'];
    }

    /**
     * Sets field
     *
     * @param string $field field
     *
     * @return self
     */
    public function setField($field)
    {
        $this->container['field'] = $field;

        return $this;
    }

    /**
     * Gets our_value
     *
     * @return string|null
     */
    public function getOurValue()
    {
        return $this->container['our_value'];
    }

    /**
     * Sets our_value
     *
     * @param string|null $our_value our_value
     *
     * @return self
     */
    public function setOurValue($our_value)
    {
        $this->container['our_value'] = $our_value;

        return $this;
    }

    /**
     * Gets remote_value
     *
     * @return string|null
     */
    public function getRemoteValue()
    {
        return $this->container['remote_value'];
    }

    /**
     * Sets remote_value
     *
     * @param string|null $remote_value remote_value
     *
     * @return self
     */
    public function setRemoteValue($remote_value)
    {
        $this->container['remote_value'] = $remote_value;

        return $this;
    }

    /**
     * Gets first_detected_at
     *
     * @return \DateTime
     */
    public function getFirstDetectedAt()
    {
        return $this->container['first_detected_at'];
    }

    /**
     * Sets first_detected_at
     *
     * @param \DateTime $first_detected_at first_detected_at
     *
     * @return self
     */
    public function setFirstDetectedAt($first_detected_at)
    {
        $this->container['first_detected_at'] = $first_detected_at;

        return $this;
    }

    /**
     * Gets last_detected_at
     *
     * @return \DateTime
     */
    public function getLastDetectedAt()
    {
        return $this->container['last_detected_at'];
    }

    /**
     * Sets last_detected_at
     *
     * @param \DateTime $last_detected_at last_detected_at
     *
     * @return self
     */
    public function setLastDetectedAt($last_detected_at)
    {
        $this->container['last_detected_at'] = $last_detected_at;

        return $this;
    }

    /**
     * Gets dismissed_at
     *
     * @return \DateTime|null
     */
    public function getDismissedAt()
    {
        return $this->container['dismissed_at'];
    }

    /**
     * Sets dismissed_at
     *
     * @param \DateTime|null $dismissed_at dismissed_at
     *
     * @return self
     */
    public function setDismissedAt($dismissed_at)
    {
        $this->container['dismissed_at'] = $dismissed_at;

        return $this;
    }

    /**
     * Gets dismissed_remote_value
     *
     * @return string|null
     */
    public function getDismissedRemoteValue()
    {
        return $this->container['dismissed_remote_value'];
    }

    /**
     * Sets dismissed_remote_value
     *
     * @param string|null $dismissed_remote_value dismissed_remote_value
     *
     * @return self
     */
    public function setDismissedRemoteValue($dismissed_remote_value)
    {
        $this->container['dismissed_remote_value'] = $dismissed_remote_value;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


