<?php
/**
 * ListActionLogCallsItem
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Crossly Seller API
 *
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Crossly\Model;

use \ArrayAccess;
use \Crossly\ObjectSerializer;

/**
 * ListActionLogCallsItem Class Doc Comment
 *
 * @category Class
 * @package  Crossly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ListActionLogCallsItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ListActionLogCallsItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'created_at' => '\DateTime',
        'user_id' => 'string',
        'platform' => 'string',
        'action' => 'string',
        'step' => 'float',
        'url' => 'string',
        'method' => 'string',
        'status_code' => 'float',
        'latency_ms' => 'float',
        'error_class' => 'string',
        'error_message' => 'string',
        'request_body_excerpt' => 'string',
        'response_body_excerpt' => 'string',
        'recipe_id' => 'string',
        'doc_id_or_hash' => 'string',
        'proxy_id' => 'string',
        'correlation_id' => 'string',
        'action_event_id' => 'string',
        'ok' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'created_at' => 'date-time',
        'user_id' => null,
        'platform' => null,
        'action' => null,
        'step' => null,
        'url' => null,
        'method' => null,
        'status_code' => null,
        'latency_ms' => null,
        'error_class' => null,
        'error_message' => null,
        'request_body_excerpt' => null,
        'response_body_excerpt' => null,
        'recipe_id' => null,
        'doc_id_or_hash' => null,
        'proxy_id' => null,
        'correlation_id' => null,
        'action_event_id' => null,
        'ok' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'created_at' => 'createdAt',
        'user_id' => 'userId',
        'platform' => 'platform',
        'action' => 'action',
        'step' => 'step',
        'url' => 'url',
        'method' => 'method',
        'status_code' => 'statusCode',
        'latency_ms' => 'latencyMs',
        'error_class' => 'errorClass',
        'error_message' => 'errorMessage',
        'request_body_excerpt' => 'requestBodyExcerpt',
        'response_body_excerpt' => 'responseBodyExcerpt',
        'recipe_id' => 'recipeId',
        'doc_id_or_hash' => 'docIdOrHash',
        'proxy_id' => 'proxyId',
        'correlation_id' => 'correlationId',
        'action_event_id' => 'actionEventId',
        'ok' => 'ok'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'created_at' => 'setCreatedAt',
        'user_id' => 'setUserId',
        'platform' => 'setPlatform',
        'action' => 'setAction',
        'step' => 'setStep',
        'url' => 'setUrl',
        'method' => 'setMethod',
        'status_code' => 'setStatusCode',
        'latency_ms' => 'setLatencyMs',
        'error_class' => 'setErrorClass',
        'error_message' => 'setErrorMessage',
        'request_body_excerpt' => 'setRequestBodyExcerpt',
        'response_body_excerpt' => 'setResponseBodyExcerpt',
        'recipe_id' => 'setRecipeId',
        'doc_id_or_hash' => 'setDocIdOrHash',
        'proxy_id' => 'setProxyId',
        'correlation_id' => 'setCorrelationId',
        'action_event_id' => 'setActionEventId',
        'ok' => 'setOk'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'created_at' => 'getCreatedAt',
        'user_id' => 'getUserId',
        'platform' => 'getPlatform',
        'action' => 'getAction',
        'step' => 'getStep',
        'url' => 'getUrl',
        'method' => 'getMethod',
        'status_code' => 'getStatusCode',
        'latency_ms' => 'getLatencyMs',
        'error_class' => 'getErrorClass',
        'error_message' => 'getErrorMessage',
        'request_body_excerpt' => 'getRequestBodyExcerpt',
        'response_body_excerpt' => 'getResponseBodyExcerpt',
        'recipe_id' => 'getRecipeId',
        'doc_id_or_hash' => 'getDocIdOrHash',
        'proxy_id' => 'getProxyId',
        'correlation_id' => 'getCorrelationId',
        'action_event_id' => 'getActionEventId',
        'ok' => 'getOk'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['created_at'] = $data['created_at'] ?? null;
        $this->container['user_id'] = $data['user_id'] ?? null;
        $this->container['platform'] = $data['platform'] ?? null;
        $this->container['action'] = $data['action'] ?? null;
        $this->container['step'] = $data['step'] ?? null;
        $this->container['url'] = $data['url'] ?? null;
        $this->container['method'] = $data['method'] ?? null;
        $this->container['status_code'] = $data['status_code'] ?? null;
        $this->container['latency_ms'] = $data['latency_ms'] ?? null;
        $this->container['error_class'] = $data['error_class'] ?? null;
        $this->container['error_message'] = $data['error_message'] ?? null;
        $this->container['request_body_excerpt'] = $data['request_body_excerpt'] ?? null;
        $this->container['response_body_excerpt'] = $data['response_body_excerpt'] ?? null;
        $this->container['recipe_id'] = $data['recipe_id'] ?? null;
        $this->container['doc_id_or_hash'] = $data['doc_id_or_hash'] ?? null;
        $this->container['proxy_id'] = $data['proxy_id'] ?? null;
        $this->container['correlation_id'] = $data['correlation_id'] ?? null;
        $this->container['action_event_id'] = $data['action_event_id'] ?? null;
        $this->container['ok'] = $data['ok'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['platform'] === null) {
            $invalidProperties[] = "'platform' can't be null";
        }
        if ($this->container['action'] === null) {
            $invalidProperties[] = "'action' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['method'] === null) {
            $invalidProperties[] = "'method' can't be null";
        }
        if ($this->container['correlation_id'] === null) {
            $invalidProperties[] = "'correlation_id' can't be null";
        }
        if ($this->container['ok'] === null) {
            $invalidProperties[] = "'ok' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string|null $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets platform
     *
     * @return string
     */
    public function getPlatform()
    {
        return $this->container['platform'];
    }

    /**
     * Sets platform
     *
     * @param string $platform platform
     *
     * @return self
     */
    public function setPlatform($platform)
    {
        $this->container['platform'] = $platform;

        return $this;
    }

    /**
     * Gets action
     *
     * @return string
     */
    public function getAction()
    {
        return $this->container['action'];
    }

    /**
     * Sets action
     *
     * @param string $action action
     *
     * @return self
     */
    public function setAction($action)
    {
        $this->container['action'] = $action;

        return $this;
    }

    /**
     * Gets step
     *
     * @return float|null
     */
    public function getStep()
    {
        return $this->container['step'];
    }

    /**
     * Sets step
     *
     * @param float|null $step step
     *
     * @return self
     */
    public function setStep($step)
    {
        $this->container['step'] = $step;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets method
     *
     * @return string
     */
    public function getMethod()
    {
        return $this->container['method'];
    }

    /**
     * Sets method
     *
     * @param string $method method
     *
     * @return self
     */
    public function setMethod($method)
    {
        $this->container['method'] = $method;

        return $this;
    }

    /**
     * Gets status_code
     *
     * @return float|null
     */
    public function getStatusCode()
    {
        return $this->container['status_code'];
    }

    /**
     * Sets status_code
     *
     * @param float|null $status_code status_code
     *
     * @return self
     */
    public function setStatusCode($status_code)
    {
        $this->container['status_code'] = $status_code;

        return $this;
    }

    /**
     * Gets latency_ms
     *
     * @return float|null
     */
    public function getLatencyMs()
    {
        return $this->container['latency_ms'];
    }

    /**
     * Sets latency_ms
     *
     * @param float|null $latency_ms latency_ms
     *
     * @return self
     */
    public function setLatencyMs($latency_ms)
    {
        $this->container['latency_ms'] = $latency_ms;

        return $this;
    }

    /**
     * Gets error_class
     *
     * @return string|null
     */
    public function getErrorClass()
    {
        return $this->container['error_class'];
    }

    /**
     * Sets error_class
     *
     * @param string|null $error_class error_class
     *
     * @return self
     */
    public function setErrorClass($error_class)
    {
        $this->container['error_class'] = $error_class;

        return $this;
    }

    /**
     * Gets error_message
     *
     * @return string|null
     */
    public function getErrorMessage()
    {
        return $this->container['error_message'];
    }

    /**
     * Sets error_message
     *
     * @param string|null $error_message error_message
     *
     * @return self
     */
    public function setErrorMessage($error_message)
    {
        $this->container['error_message'] = $error_message;

        return $this;
    }

    /**
     * Gets request_body_excerpt
     *
     * @return string|null
     */
    public function getRequestBodyExcerpt()
    {
        return $this->container['request_body_excerpt'];
    }

    /**
     * Sets request_body_excerpt
     *
     * @param string|null $request_body_excerpt request_body_excerpt
     *
     * @return self
     */
    public function setRequestBodyExcerpt($request_body_excerpt)
    {
        $this->container['request_body_excerpt'] = $request_body_excerpt;

        return $this;
    }

    /**
     * Gets response_body_excerpt
     *
     * @return string|null
     */
    public function getResponseBodyExcerpt()
    {
        return $this->container['response_body_excerpt'];
    }

    /**
     * Sets response_body_excerpt
     *
     * @param string|null $response_body_excerpt response_body_excerpt
     *
     * @return self
     */
    public function setResponseBodyExcerpt($response_body_excerpt)
    {
        $this->container['response_body_excerpt'] = $response_body_excerpt;

        return $this;
    }

    /**
     * Gets recipe_id
     *
     * @return string|null
     */
    public function getRecipeId()
    {
        return $this->container['recipe_id'];
    }

    /**
     * Sets recipe_id
     *
     * @param string|null $recipe_id recipe_id
     *
     * @return self
     */
    public function setRecipeId($recipe_id)
    {
        $this->container['recipe_id'] = $recipe_id;

        return $this;
    }

    /**
     * Gets doc_id_or_hash
     *
     * @return string|null
     */
    public function getDocIdOrHash()
    {
        return $this->container['doc_id_or_hash'];
    }

    /**
     * Sets doc_id_or_hash
     *
     * @param string|null $doc_id_or_hash doc_id_or_hash
     *
     * @return self
     */
    public function setDocIdOrHash($doc_id_or_hash)
    {
        $this->container['doc_id_or_hash'] = $doc_id_or_hash;

        return $this;
    }

    /**
     * Gets proxy_id
     *
     * @return string|null
     */
    public function getProxyId()
    {
        return $this->container['proxy_id'];
    }

    /**
     * Sets proxy_id
     *
     * @param string|null $proxy_id proxy_id
     *
     * @return self
     */
    public function setProxyId($proxy_id)
    {
        $this->container['proxy_id'] = $proxy_id;

        return $this;
    }

    /**
     * Gets correlation_id
     *
     * @return string
     */
    public function getCorrelationId()
    {
        return $this->container['correlation_id'];
    }

    /**
     * Sets correlation_id
     *
     * @param string $correlation_id correlation_id
     *
     * @return self
     */
    public function setCorrelationId($correlation_id)
    {
        $this->container['correlation_id'] = $correlation_id;

        return $this;
    }

    /**
     * Gets action_event_id
     *
     * @return string|null
     */
    public function getActionEventId()
    {
        return $this->container['action_event_id'];
    }

    /**
     * Sets action_event_id
     *
     * @param string|null $action_event_id action_event_id
     *
     * @return self
     */
    public function setActionEventId($action_event_id)
    {
        $this->container['action_event_id'] = $action_event_id;

        return $this;
    }

    /**
     * Gets ok
     *
     * @return bool
     */
    public function getOk()
    {
        return $this->container['ok'];
    }

    /**
     * Sets ok
     *
     * @param bool $ok ok
     *
     * @return self
     */
    public function setOk($ok)
    {
        $this->container['ok'] = $ok;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


